interface CountryPhonePattern {
  code: string;
  name: string;
  pattern: RegExp;
  flag: string;
  dialing_code: string;
  maxDigits?: number;
  continent?: string;

  //  postalCodePattern: RegExp;
}

export const CountryPhone: CountryPhonePattern[] = [
  {
    code: "AF",
    name: "Afghanistan",
    pattern: /^\+93[0-9]{9,10}$/,
    flag: "🇦🇫",
    dialing_code: "+93",
    maxDigits: 10,
    continent: "Asia",
  },
  {
    code: "AL",
    name: "Albania",
    pattern: /^\+355[0-9]{8,9}$/,
    flag: "🇦🇱",
    dialing_code: "+355",
    maxDigits: 9,
    continent: "Europe",
  },
  {
    code: "DZ",
    name: "Algeria",
    pattern: /^\+213[0-9]{9}$/,
    flag: "🇩🇿",
    dialing_code: "+213",
    maxDigits: 9,
    continent: "Africa",
  },
  {
    code: "AD",
    name: "Andorra",
    pattern: /^\+376[0-9]{6}$/,
    flag: "🇦🇩",
    dialing_code: "+376",
    maxDigits: 6,
    continent: "Europe",
  },
  {
    code: "AO",
    name: "Angola",
    pattern: /^\+244[0-9]{9}$/,
    flag: "🇦🇴",
    dialing_code: "+244",
    maxDigits: 9,
    continent: "Africa",
  },
  {
    code: "AI",
    name: "Anguilla",
    pattern: /^\+1[264][0-9]{7}$/,
    flag: "🇦🇮",
    dialing_code: "+1-264",
    maxDigits: 7,
    continent: "North America",
  },
  {
    code: "AR",
    name: "Argentina",
    pattern: /^\+54[0-9]{10}$/,
    flag: "🇦🇷",
    dialing_code: "+54",
    maxDigits: 10,
    continent: "South America",
  },
  {
    code: "AM",
    name: "Armenia",
    pattern: /^\+374[0-9]{8}$/,
    flag: "🇦🇲",
    dialing_code: "+374",
    maxDigits: 8,
    continent: "Asia",
  },
  {
    code: "AW",
    name: "Aruba",
    pattern: /^\+297[0-9]{7}$/,
    flag: "🇦🇼",
    dialing_code: "+297",
    maxDigits: 7,
    continent: "North America",
  },
  {
    code: "AU",
    name: "Australia",
    pattern: /^\+61[0-9]{9}$/,
    flag: "🇦🇺",
    dialing_code: "+61",
    maxDigits: 9,
    continent: "Australia",
  },
  {
    code: "AT",
    name: "Austria",
    pattern: /^\+43[0-9]{4,13}$/,
    flag: "🇦🇹",
    dialing_code: "+43",
    maxDigits: 13,
    continent: "Europe",
  },
  {
    code: "AZ",
    name: "Azerbaijan",
    pattern: /^\+994[0-9]{9}$/,
    flag: "🇦🇿",
    dialing_code: "+994",
    maxDigits: 9,
    continent: "Asia",
  },
  {
    code: "BS",
    name: "Bahamas",
    pattern: /^\+1[242][0-9]{7}$/,
    flag: "🇧🇸",
    dialing_code: "+1-242",
    maxDigits: 7,
    continent: "North America",
  },
  {
    code: "BH",
    name: "Bahrain",
    pattern: /^\+973[0-9]{8}$/,
    flag: "🇧🇭",
    dialing_code: "+973",
    maxDigits: 8,
    continent: "MiddleEast",
  },
  {
    code: "BD",
    name: "Bangladesh",
    pattern: /^\+880[0-9]{10}$/,
    flag: "🇧🇩",
    dialing_code: "+880",
    maxDigits: 10,
    continent: "Asia",
  },
  {
    code: "BB",
    name: "Barbados",
    pattern: /^\+1[246][0-9]{7}$/,
    flag: "🇧🇧",
    dialing_code: "+1-246",
    maxDigits: 7,
    continent: "North America",
  },
  {
    code: "BY",
    name: "Belarus",
    pattern: /^\+375[0-9]{9}$/,
    flag: "🇧🇾",
    dialing_code: "+375",
    maxDigits: 9,
    continent: "Europe",
  },
  {
    code: "BE",
    name: "Belgium",
    pattern: /^\+32[0-9]{8,9}$/,
    flag: "🇧🇪",
    dialing_code: "+32",
    maxDigits: 9,
    continent: "Europe",
  },
  {
    code: "BZ",
    name: "Belize",
    pattern: /^\+501[0-9]{7}$/,
    flag: "🇧🇿",
    dialing_code: "+501",
    maxDigits: 7,
    continent: "North America",
  },
  {
    code: "BJ",
    name: "Benin",
    pattern: /^\+229[0-9]{8}$/,
    flag: "🇧🇯",
    dialing_code: "+229",
    maxDigits: 8,
    continent: "Africa",
  },
  {
    code: "BM",
    name: "Bermuda",
    pattern: /^\+1[441][0-9]{7}$/,
    flag: "🇧🇲",
    dialing_code: "+1-441",
    maxDigits: 7,
    continent: "North America",
  },
  {
    code: "BT",
    name: "Bhutan",
    pattern: /^\+975[0-9]{8}$/,
    flag: "🇧🇹",
    dialing_code: "+975",
    maxDigits: 8,
    continent: "Asia",
  },
  {
    code: "BO",
    name: "Bolivia",
    pattern: /^\+591[0-9]{8}$/,
    flag: "🇧🇴",
    dialing_code: "+591",
    maxDigits: 8,
    continent: "South America",
  },
  {
    code: "BA",
    name: "Bosnia and Herzegovina",
    pattern: /^\+387[0-9]{8}$/,
    flag: "🇧🇦",
    dialing_code: "+387",
    maxDigits: 8,
    continent: "Europe",
  },
  {
    code: "BW",
    name: "Botswana",
    pattern: /^\+267[0-9]{7}$/,
    flag: "🇧🇼",
    dialing_code: "+267",
    maxDigits: 7,
    continent: "Africa",
  },
  {
    code: "BR",
    name: "Brazil",
    pattern: /^\+55[0-9]{10,11}$/,
    flag: "🇧🇷",
    dialing_code: "+55",
    maxDigits: 11,
    continent: "South America",
  },
  {
    code: "BN",
    name: "Brunei Darussalam",
    pattern: /^\+673[0-9]{7}$/,
    flag: "🇧🇳",
    dialing_code: "+673",
    maxDigits: 7,
    continent: "Asia",
  },
  {
    code: "BG",
    name: "Bulgaria",
    pattern: /^\+359[0-9]{8,9}$/,
    flag: "🇧🇬",
    dialing_code: "+359",
    maxDigits: 9,
    continent: "Europe",
  },

  {
    code: "BF",
    name: "Burkina Faso",
    pattern: /^\+226[0-9]{8}$/,
    flag: "🇧🇫",
    dialing_code: "+226",
    maxDigits: 8,
    continent: "Africa",
  },
  {
    code: "BI",
    name: "Burundi",
    pattern: /^\+257[0-9]{7}$/,
    flag: "🇧🇮",
    dialing_code: "+257",
    maxDigits: 7,
    continent: "Africa",
  },
  {
    code: "KH",
    name: "Cambodia",
    pattern: /^\+855[0-9]{8,9}$/,
    flag: "🇰🇭",
    dialing_code: "+855",
    maxDigits: 9,
    continent: "Asia",
  },
  {
    code: "CM",
    name: "Cameroon",
    pattern: /^\+237[0-9]{9}$/,
    flag: "🇨🇲",
    dialing_code: "+237",
    maxDigits: 9,
    continent: "Africa",
  },
  {
    code: "CA",
    name: "Canada",
    pattern: /^\+1[0-9]{10}$/,
    flag: "🇨🇦",
    dialing_code: "+1",
    maxDigits: 10,
    continent: "North America",
  },
  {
    code: "CV",
    name: "Cape Verde",
    pattern: /^\+238[0-9]{6}$/,
    flag: "🇨🇻",
    dialing_code: "+238",
    maxDigits: 6,
    continent: "Africa",
  },
  {
    code: "KY",
    name: "Cayman Islands",
    pattern: /^\+1[345][0-9]{7}$/,
    flag: "🇰🇾",
    dialing_code: "+1-345",
    maxDigits: 7,
    continent: "North America",
  },
  {
    code: "CF",
    name: "Central African Republic",
    pattern: /^\+236[0-9]{8}$/,
    flag: "🇨🇫",
    dialing_code: "+236",
    maxDigits: 8,
    continent: "Africa",
  },
  {
    code: "TD",
    name: "Chad",
    pattern: /^\+235[0-9]{8}$/,
    flag: "🇹🇩",
    dialing_code: "+235",
    maxDigits: 8,
    continent: "Africa",
  },
  {
    code: "CL",
    name: "Chile",
    pattern: /^\+56[0-9]{9}$/,
    flag: "🇨🇱",
    dialing_code: "+56",
    maxDigits: 9,
    continent: "South America",
  },
  {
    code: "CN",
    name: "China",
    pattern: /^\+86[0-9]{11}$/,
    flag: "🇨🇳",
    dialing_code: "+86",
    maxDigits: 11,
    continent: "Asia",
  },
  {
    code: "CX",
    name: "Christmas Island",
    pattern: /^\+61[0-9]{9}$/,
    flag: "🇨🇽",
    dialing_code: "+61",
    maxDigits: 9,
    continent: "Australia",
  },
  {
    code: "CC",
    name: "Cocos (Keeling) Islands",
    pattern: /^\+61[0-9]{9}$/,
    flag: "🇨🇨",
    dialing_code: "+61",
    maxDigits: 9,
    continent: "Australia",
  },
  {
    code: "CO",
    name: "Colombia",
    pattern: /^\+57[0-9]{10}$/,
    flag: "🇨🇴",
    dialing_code: "+57",
    maxDigits: 10,
    continent: "South America",
  },
  {
    code: "KM",
    name: "Comoros",
    pattern: /^\+269[0-9]{7}$/,
    flag: "🇰🇲",
    dialing_code: "+269",
    maxDigits: 7,
    continent: "Africa",
  },
  {
    code: "CG",
    name: "Congo",
    pattern: /^\+242[0-9]{7,8}$/,
    flag: "🇨🇬",
    dialing_code: "+242",
    maxDigits: 8,
    continent: "Africa",
  },
  {
    code: "CD",
    name: "Congo, Democratic Republic of the",
    pattern: /^\+243[0-9]{9}$/,
    flag: "🇨🇩",
    dialing_code: "+243",
    maxDigits: 9,
    continent: "Africa",
  },

  {
    code: "CK",
    name: "Cook Islands",
    pattern: /^\+682[0-9]{5}$/,
    flag: "🇨🇰",
    dialing_code: "+682",
    maxDigits: 5,
    continent: "Oceania",
  },
  {
    code: "CR",
    name: "Costa Rica",
    pattern: /^\+506[0-9]{8}$/,
    flag: "🇨🇷",
    dialing_code: "+506",
    maxDigits: 8,
    continent: "North America",
  },
  {
    code: "HR",
    name: "Croatia",
    pattern: /^\+385[0-9]{9}$/,
    flag: "🇭🇷",
    dialing_code: "+385",
    maxDigits: 9,
    continent: "Europe",
  },
  {
    code: "CU",
    name: "Cuba",
    pattern: /^\+53[0-9]{8}$/,
    flag: "🇨🇺",
    dialing_code: "+53",
    maxDigits: 8,
    continent: "North America",
  },
  {
    code: "CW",
    name: "Curacao",
    pattern: /^\+599[0-9]{7}$/,
    flag: "🇨🇼",
    dialing_code: "+599",
    maxDigits: 7,
    continent: "North America",
  },
  {
    code: "CY",
    name: "Cyprus",
    pattern: /^\+357[0-9]{8}$/,
    flag: "🇨🇾",
    dialing_code: "+357",
    maxDigits: 8,
    continent: "Europe",
  },
  {
    code: "CZ",
    name: "Czech Republic",
    pattern: /^\+420[0-9]{9}$/,
    flag: "🇨🇿",
    dialing_code: "+420",
    maxDigits: 9,
    continent: "Europe",
  },
  {
    code: "DK",
    name: "Denmark",
    pattern: /^\+45[0-9]{8}$/,
    flag: "🇩🇰",
    dialing_code: "+45",
    maxDigits: 8,
    continent: "Europe",
  },
  {
    code: "DJ",
    name: "Djibouti",
    pattern: /^\+253[0-9]{6}$/,
    flag: "🇩🇯",
    dialing_code: "+253",
    maxDigits: 6,
    continent: "Africa",
  },
  {
    code: "DM",
    name: "Dominica",
    pattern: /^\+1[767][0-9]{7}$/,
    flag: "🇩🇲",
    dialing_code: "+1-767",
    maxDigits: 7,
    continent: "North America",
  },
  {
    code: "DO",
    name: "Dominican Republic",
    pattern: /^\+1[809|829|849][0-9]{7}$/,
    flag: "🇩🇴",
    dialing_code: "+1-809",
    maxDigits: 7,
    continent: "North America",
  },
  {
    code: "EC",
    name: "Ecuador",
    pattern: /^\+593[0-9]{9}$/,
    flag: "🇪🇨",
    dialing_code: "+593",
    maxDigits: 9,
    continent: "South America",
  },
  {
    code: "EG",
    name: "Egypt",
    pattern: /^\+20[0-9]{10}$/,
    flag: "🇪🇬",
    dialing_code: "+20",
    maxDigits: 10,
    continent: "Africa",
  },
  {
    code: "SV",
    name: "El Salvador",
    pattern: /^\+503[0-9]{8}$/,
    flag: "🇸🇻",
    dialing_code: "+503",
    maxDigits: 8,
    continent: "North America",
  },
  {
    code: "GQ",
    name: "Equatorial Guinea",
    pattern: /^\+240[0-9]{4,9}$/,
    flag: "🇲🇱",
    dialing_code: "+240",
    maxDigits: 9,
    continent: "Africa",
  },
  {
    code: "ER",
    name: "Eritrea",
    pattern: /^\+291[0-9]{7}$/,
    flag: "🇪🇷",
    dialing_code: "+291",
    maxDigits: 7,
    continent: "Africa",
  },
  {
    code: "EE",
    name: "Estonia",
    pattern: /^\+372[0-9]{7}$/,
    flag: "🇪🇪",
    dialing_code: "+372",
    maxDigits: 7,
    continent: "Europe",
  },
  {
    code: "ET",
    name: "Ethiopia",
    pattern: /^\+251[0-9]{9}$/,
    flag: "🇪🇹",
    dialing_code: "+251",
    maxDigits: 9,
    continent: "Africa",
  },
  {
    code: "FK",
    name: "Falkland Islands",
    pattern: /^\+500[0-9]{4}$/,
    flag: "🇫🇰",
    dialing_code: "+500",
    maxDigits: 4,
    continent: "South America",
  },
  {
    code: "FO",
    name: "Faroe Islands",
    pattern: /^\+298[0-9]{6}$/,
    flag: "🇫🇴",
    dialing_code: "+298",
    maxDigits: 6,
    continent: "Europe",
  },
  {
    code: "FJ",
    name: "Fiji",
    pattern: /^\+679[0-9]{6}$/,
    flag: "🇫🇯",
    dialing_code: "+679",
    maxDigits: 6,
    continent: "Oceania",
  },
  {
    code: "FI",
    name: "Finland",
    pattern: /^\+358[0-9]{5,12}$/,
    flag: "🇫🇮",
    dialing_code: "+358",
    maxDigits: 12,
    continent: "Europe",
  },
  {
    code: "FR",
    name: "France",
    pattern: /^\+33[0-9]{9}$/,
    flag: "🇫🇷",
    dialing_code: "+33",
    maxDigits: 9,
    continent: "Europe",
  },
  {
    code: "GF",
    name: "French Guiana",
    pattern: /^\+594[0-9]{9}$/,
    flag: "🇬🇫",
    dialing_code: "+594",
    maxDigits: 9,
    continent: "South America",
  },
  {
    code: "PF",
    name: "French Polynesia",
    pattern: /^\+689[0-9]{6}$/,
    flag: "🇵🇫",
    dialing_code: "+689",
    maxDigits: 6,
    continent: "Oceania",
  },
  {
    code: "GA",
    name: "Gabon",
    pattern: /^\+241[0-9]{7}$/,
    flag: "🇬🇦",
    dialing_code: "+241",
    maxDigits: 7,
    continent: "Africa",
  },
  {
    code: "GM",
    name: "Gambia",
    pattern: /^\+220[0-9]{7}$/,
    flag: "🇬🇲",
    dialing_code: "+220",
    maxDigits: 8,
    continent: "Africa",
  },
  {
    code: "GE",
    name: "Georgia",
    pattern: /^\+995[0-9]{9}$/,
    flag: "🇬🇪",
    dialing_code: "+995",
    maxDigits: 9,
    continent: "Europe",
  },
  {
    code: "DE",
    name: "Germany",
    pattern: /^\+49[0-9]{10,11}$/,
    flag: "🇩🇪",
    dialing_code: "+49",
    maxDigits: 11,
    continent: "Europe",
  },
  {
    code: "GH",
    name: "Ghana",
    pattern: /^\+233[0-9]{9}$/,
    flag: "🇬🇭",
    dialing_code: "+233",
    maxDigits: 9,
    continent: "Africa",
  },
  {
    code: "GI",
    name: "Gibraltar",
    pattern: /^\+350[0-9]{4,7}$/,
    flag: "🇬🇮",
    dialing_code: "+350",
    maxDigits: 7,
    continent: "Europe",
  },
  {
    code: "GR",
    name: "Greece",
    pattern: /^\+30[0-9]{10}$/,
    flag: "🇬🇷",
    dialing_code: "+30",
    maxDigits: 10,
    continent: "Europe",
  },
  {
    code: "GL",
    name: "Greenland",
    pattern: /^\+299[0-9]{6}$/,
    flag: "🇬🇱",
    dialing_code: "+299",
    maxDigits: 6,
    continent: "North America",
  },
  {
    code: "GT",
    name: "Guatemala",
    pattern: /^\+502[0-9]{8}$/,
    flag: "🇬🇹",
    dialing_code: "+502",
    maxDigits: 8,
    continent: "North America",
  },
  {
    code: "GN",
    name: "Guinea",
    pattern: /^\+224[0-9]{9}$/,
    flag: "🇬🇳",
    dialing_code: "+224",
    maxDigits: 9,
    continent: "Africa",
  },
  {
    code: "GW",
    name: "Guinea-Bissau",
    pattern: /^\+245[0-9]{7}$/,
    flag: "🇬🇼",
    dialing_code: "+245",
    maxDigits: 7,
    continent: "Africa",
  },
  {
    code: "GY",
    name: "Guyana",
    pattern: /^\+592[0-9]{7}$/,
    flag: "🇬🇾",
    dialing_code: "+592",
    maxDigits: 7,
    continent: "South America",
  },
  {
    code: "HT",
    name: "Haiti",
    pattern: /^\+509[0-9]{8}$/,
    flag: "🇭🇹",
    dialing_code: "+509",
    maxDigits: 8,
    continent: "North America",
  },
  {
    code: "HN",
    name: "Honduras",
    pattern: /^\+504[0-9]{8}$/,
    flag: "🇭🇳",
    dialing_code: "+504",
    maxDigits: 8,
    continent: "North America",
  },
  {
    code: "HK",
    name: "Hong Kong",
    pattern: /^\+852[0-9]{8}$/,
    flag: "🇭🇰",
    dialing_code: "+852",
    maxDigits: 8,
    continent: "Asia",
  },
  {
    code: "HU",
    name: "Hungary",
    pattern: /^\+36[0-9]{9}$/,
    flag: "🇭🇺",
    dialing_code: "+36",
    maxDigits: 9,
    continent: "Europe",
  },
  {
    code: "IS",
    name: "Iceland",
    pattern: /^\+354[0-9]{7}$/,
    flag: "🇮🇸",
    dialing_code: "+354",
    maxDigits: 7,
    continent: "Europe",
  },
  {
    code: "IN",
    name: "India",
    pattern: /^\+91[0-9]{10}$/,
    flag: "🇮🇳",
    dialing_code: "+91",
    maxDigits: 10,
    continent: "Asia",
  },
  {
    code: "ID",
    name: "Indonesia",
    pattern: /^\+62[0-9]{8,11}$/,
    flag: "🇮🇩",
    dialing_code: "+62",
    maxDigits: 11,
    continent: "Asia",
  },
  {
    code: "IR",
    name: "Iran",
    pattern: /^\+98[0-9]{10}$/,
    flag: "🇮🇷",
    dialing_code: "+98",
    maxDigits: 10,
    continent: "MiddleEast",
  },
  {
    code: "IQ",
    name: "Iraq",
    pattern: /^\+964[0-9]{8}$/,
    flag: "🇮🇶",
    dialing_code: "+964",
    maxDigits: 8,
    continent: "MiddleEast",
  },
  {
    code: "IE",
    name: "Ireland",
    pattern: /^\+353[0-9]{7,9}$/,
    flag: "🇮🇪",
    dialing_code: "+353",
    maxDigits: 9,
    continent: "Europe",
  },
  {
    code: "IL",
    name: "Israel",
    pattern: /^\+972[0-9]{7,9}$/,
    flag: "🇮🇱",
    dialing_code: "+972",
    maxDigits: 9,
    continent: "MiddleEast",
  },
  {
    code: "IT",
    name: "Italy",
    pattern: /^\+39[0-9]{10}$/,
    flag: "🇮🇹",
    dialing_code: "+39",
    maxDigits: 10,
    continent: "Europe",
  },
  {
    code: "GY",
    name: "Guyana",
    pattern: /^\+592[0-9]{7}$/,
    flag: "🇬🇾",
    dialing_code: "+592",
    maxDigits: 8,
    continent: "South America",
  },
  {
    code: "HT",
    name: "Haiti",
    pattern: /^\+509[0-9]{8}$/,
    flag: "🇭🇹",
    dialing_code: "+509",
    maxDigits: 8,
    continent: "North America",
  },
  {
    code: "HN",
    name: "Honduras",
    pattern: /^\+504[0-9]{8}$/,
    flag: "🇭🇳",
    dialing_code: "+504",
    maxDigits: 8,
    continent: "North America",
  },
  {
    code: "HK",
    name: "Hong Kong",
    pattern: /^\+852[0-9]{8}$/,
    flag: "🇭🇰",
    dialing_code: "+852",
    maxDigits: 8,
    continent: "Asia",
  },
  {
    code: "HU",
    name: "Hungary",
    pattern: /^\+36[0-9]{9}$/,
    flag: "🇭🇺",
    dialing_code: "+36",
    maxDigits: 9,
    continent: "Europe",
  },
  {
    code: "IS",
    name: "Iceland",
    pattern: /^\+354[0-9]{5}$/,
    flag: "🇮🇸",
    dialing_code: "+354",
    maxDigits: 5,
    continent: "Europe",
  },

  {
    code: "ID",
    name: "Indonesia",
    pattern: /^\+62[0-9]{10,12}$/,
    flag: "🇮🇩",
    dialing_code: "+62",
    maxDigits: 12,
    continent: "Asia",
  },
  {
    code: "IR",
    name: "Iran",
    pattern: /^\+98[0-9]{10}$/,
    flag: "🇮🇷",
    dialing_code: "+98",
    maxDigits: 10,
    continent: "Asia",
  },
  {
    code: "IQ",
    name: "Iraq",
    pattern: /^\+964[0-9]{8}$/,
    flag: "🇮🇶",
    dialing_code: "+964",
    maxDigits: 8,
    continent: "Asia",
  },
  {
    code: "IE",
    name: "Ireland",
    pattern: /^\+353[0-9]{7,9}$/,
    flag: "🇮🇪",
    dialing_code: "+353",
    maxDigits: 9,
    continent: "Europe",
  },
  {
    code: "IL",
    name: "Israel",
    pattern: /^\+972[0-9]{9}$/,
    flag: "🇮🇱",
    dialing_code: "+972",
    maxDigits: 9,
    continent: "Asia",
  },
  {
    code: "IT",
    name: "Italy",
    pattern: /^\+39[0-9]{10}$/,
    flag: "🇮🇹",
    dialing_code: "+39",
    maxDigits: 10,
    continent: "Europe",
  },
  {
    code: "JE",
    name: "Jersey",
    pattern: /^\+44[0-1534][0-9]{5,7}$/,
    flag: "🇯🇪",
    dialing_code: "+44-1534",
    maxDigits: 7,
    continent: "Europe",
  },
  {
    code: "JO",
    name: "Jordan",
    pattern: /^\+962[0-9]{9}$/,
    flag: "🇯🇴",
    dialing_code: "+962",
    maxDigits: 9,
    continent: "MiddleEast",
  },
  {
    code: "KZ",
    name: "Kazakhstan",
    pattern: /^\+7[0-9]{10}$/,
    flag: "🇰🇿",
    dialing_code: "+7",
    maxDigits: 10,
    continent: "Asia",
  },
  {
    code: "KE",
    name: "Kenya",
    pattern: /^\+254[0-9]{9}$/,
    flag: "🇰🇪",
    dialing_code: "+254",
    maxDigits: 9,
    continent: "Africa",
  },
  {
    code: "KI",
    name: "Kiribati",
    pattern: /^\+686[0-9]{5}$/,
    flag: "🇰🇮",
    dialing_code: "+686",
    maxDigits: 5,
    continent: "Oceania",
  },
  {
    code: "KR",
    name: "Korea, Republic of",
    pattern: /^\+82[0-9]{9,10}$/,
    flag: "🇰🇷",
    dialing_code: "+82",
    maxDigits: 10,
    continent: "Asia",
  },
  {
    code: "KP",
    name: "Korea, Democratic People's Republic of",
    pattern: /^\+850[0-9]{8}$/,
    flag: "🇰🇵",
    dialing_code: "+850",
    maxDigits: 9,
    continent: "Asia",
  },
  {
    code: "KW",
    name: "Kuwait",
    pattern: /^\+965[0-9]{8}$/,
    flag: "🇰🇼",
    dialing_code: "+965",
    maxDigits: 9,
    continent: "MiddleEast",
  },
  {
    code: "KG",
    name: "Kyrgyzstan",
    pattern: /^\+996[0-9]{9}$/,
    flag: "🇰🇬",
    dialing_code: "+996",
    maxDigits: 9,
    continent: "Asia",
  },
  {
    code: "LA",
    name: "Lao People's Democratic Republic",
    pattern: /^\+856[0-9]{8,9}$/,
    flag: "🇱🇦",
    dialing_code: "+856",
    maxDigits: 9,
    continent: "Asia",
  },
  {
    code: "LV",
    name: "Latvia",
    pattern: /^\+371[0-9]{8}$/,
    flag: "🇱🇻",
    dialing_code: "+371",
    maxDigits: 9,
    continent: "Europe",
  },
  {
    code: "LB",
    name: "Lebanon",
    pattern: /^\+961[0-9]{8}$/,
    flag: "🇱🇧",
    dialing_code: "+961",
    maxDigits: 9,
    continent: "MiddleEast",
  },
  {
    code: "LS",
    name: "Lesotho",
    pattern: /^\+266[0-9]{8}$/,
    flag: "🇱🇸",
    dialing_code: "+266",
    maxDigits: 9,
    continent: "Africa",
  },
  {
    code: "LR",
    name: "Liberia",
    pattern: /^\+231[0-9]{7}$/,
    flag: "🇱🇷",
    dialing_code: "+231",
    maxDigits: 9,
    continent: "Africa",
  },
  {
    code: "LY",
    name: "Libya",
    pattern: /^\+218[0-9]{8}$/,
    flag: "🇱🇾",
    dialing_code: "+218",
    maxDigits: 9,
    continent: "MiddleEast",
  },
  {
    code: "LI",
    name: "Liechtenstein",
    pattern: /^\+423[0-9]{6}$/,
    flag: "🇱🇮",
    dialing_code: "+423",
    maxDigits: 9,
    continent: "Europe",
  },

  {
    code: "LT",
    name: "Lithuania",
    pattern: /^\+370[0-9]{8}$/,
    flag: "🇱🇹",
    dialing_code: "+370",
    maxDigits: 9,
    continent: "Europe",
  },
  {
    code: "LU",
    name: "Luxembourg",
    pattern: /^\+352[0-9]{6,8}$/,
    flag: "🇱🇺",
    dialing_code: "+352",
    maxDigits: 9,
    continent: "Europe",
  },
  {
    code: "MO",
    name: "Macao",
    pattern: /^\+853[0-9]{8}$/,
    flag: "🇲🇴",
    dialing_code: "+853",
    maxDigits: 9,
    continent: "Asia",
  },
  {
    code: "MK",
    name: "North Macedonia",
    pattern: /^\+389[0-9]{8}$/,
    flag: "🇲🇰",
    dialing_code: "+389",
    maxDigits: 9,
    continent: "Europe",
  },
  {
    code: "MG",
    name: "Madagascar",
    pattern: /^\+261[0-9]{9}$/,
    flag: "🇲🇬",
    dialing_code: "+261",
    maxDigits: 9,
    continent: "Africa",
  },
  {
    code: "MW",
    name: "Malawi",
    pattern: /^\+265[0-9]{9}$/,
    flag: "🇲🇼",
    dialing_code: "+265",
    maxDigits: 9,
    continent: "Africa",
  },
  {
    code: "MY",
    name: "Malaysia",
    pattern: /^\+60[0-9]{9,10}$/,
    flag: "🇲🇾",
    dialing_code: "+60",
    maxDigits: 10,
    continent: "Asia",
  },
  {
    code: "MV",
    name: "Maldives",
    pattern: /^\+960[0-9]{7}$/,
    flag: "🇲🇻",
    dialing_code: "+960",
    maxDigits: 9,
    continent: "Asia",
  },
  {
    code: "ML",
    name: "Mali",
    pattern: /^\+223[0-9]{8}$/,
    flag: "🇲🇱",
    dialing_code: "+223",
    maxDigits: 9,
    continent: "Africa",
  },
  {
    code: "MT",
    name: "Malta",
    pattern: /^\+356[0-9]{8}$/,
    flag: "🇲🇹",
    dialing_code: "+356",
    maxDigits: 9,
    continent: "Europe",
  },
  {
    code: "MH",
    name: "Marshall Islands",
    pattern: /^\+692[0-9]{7}$/,
    flag: "🇲🇭",
    dialing_code: "+692",
    maxDigits: 9,
    continent: "Oceania",
  },
  {
    code: "MQ",
    name: "Martinique",
    pattern: /^\+596[0-9]{9}$/,
    flag: "🇲🇶",
    dialing_code: "+596",
    maxDigits: 9,
    continent: "North America",
  },
  {
    code: "MR",
    name: "Mauritania",
    pattern: /^\+222[0-9]{8}$/,
    flag: "🇲🇷",
    dialing_code: "+222",
    maxDigits: 9,
    continent: "Africa",
  },
  {
    code: "MU",
    name: "Mauritius",
    pattern: /^\+230[0-9]{8}$/,
    flag: "🇲🇺",
    dialing_code: "+230",
    maxDigits: 9,
    continent: "Africa",
  },
  {
    code: "YT",
    name: "Mayotte",
    pattern: /^\+262[0-9]{9}$/,
    flag: "🇲🇶",
    dialing_code: "+262",
    maxDigits: 9,
    continent: "Africa",
  },
  {
    code: "MX",
    name: "Mexico",
    pattern: /^\+52[0-9]{10}$/,
    flag: "🇲🇽",
    dialing_code: "+52",
    maxDigits: 10,
    continent: "North America",
  },
  {
    code: "FM",
    name: "Micronesia",
    pattern: /^\+691[0-9]{7}$/,
    flag: "🇫🇲",
    dialing_code: "+691",
    maxDigits: 7,
    continent: "Oceania",
  },
  {
    code: "MD",
    name: "Moldova",
    pattern: /^\+373[0-9]{8}$/,
    flag: "🇲🇩",
    dialing_code: "+373",
    maxDigits: 9,
    continent: "Europe",
  },
  {
    code: "MC",
    name: "Monaco",
    pattern: /^\+377[0-9]{7}$/,
    flag: "🇲🇨",
    dialing_code: "+377",
    maxDigits: 9,
    continent: "Europe",
  },
  {
    code: "MN",
    name: "Mongolia",
    pattern: /^\+976[0-9]{8}$/,
    flag: "🇲🇳",
    dialing_code: "+976",
    maxDigits: 9,
    continent: "Asia",
  },
  {
    code: "ME",
    name: "Montenegro",
    pattern: /^\+382[0-9]{8}$/,
    flag: "🇲🇪",
    dialing_code: "+382",
    maxDigits: 9,
    continent: "Europe",
  },
  {
    code: "MS",
    name: "Montserrat",
    pattern: /^\+1[664][0-9]{7}$/,
    flag: "🇲🇸",
    dialing_code: "+1-664",
    maxDigits: 9,
    continent: "North America",
  },
  {
    code: "MA",
    name: "Morocco",
    pattern: /^\+212[0-9]{9}$/,
    flag: "🇲🇦",
    dialing_code: "+212",
    maxDigits: 9,
    continent: "Africa",
  },
  {
    code: "MZ",
    name: "Mozambique",
    pattern: /^\+258[0-9]{9}$/,
    flag: "🇲🇿",
    dialing_code: "+258",
    maxDigits: 9,
    continent: "Africa",
  },
  {
    code: "MM",
    name: "Myanmar",
    pattern: /^\+95[0-9]{9}$/,
    flag: "🇲🇲",
    dialing_code: "+95",
    maxDigits: 9,
    continent: "Asia",
  },
  {
    code: "NA",
    name: "Namibia",
    pattern: /^\+264[0-9]{9}$/,
    flag: "🇳🇦",
    dialing_code: "+264",
    maxDigits: 9,
    continent: "Africa",
  },
  {
    code: "NR",
    name: "Nauru",
    pattern: /^\+674[0-9]{7}$/,
    flag: "🇳🇷",
    dialing_code: "+674",
    maxDigits: 7,
    continent: "Oceania",
  },
  {
    code: "NP",
    name: "Nepal",
    pattern: /^\+977[0-9]{10}$/,
    flag: "🇳🇵",
    dialing_code: "+977",
    maxDigits: 10,
    continent: "Asia",
  },
  {
    code: "NL",
    name: "Netherlands",
    pattern: /^\+31[0-9]{9}$/,
    flag: "🇳🇱",
    dialing_code: "+31",
    maxDigits: 9,
    continent: "Europe",
  },
  {
    code: "NC",
    name: "New Caledonia",
    pattern: /^\+687[0-9]{6}$/,
    flag: "🇳🇨",
    dialing_code: "+687",
    maxDigits: 9,
    continent: "Oceania",
  },
  {
    code: "NZ",
    name: "New Zealand",
    pattern: /^\+64[0-9]{9}$/,
    flag: "🇳🇿",
    dialing_code: "+64",
    maxDigits: 9,
    continent: "Oceania",
  },
  {
    code: "NI",
    name: "Nicaragua",
    pattern: /^\+505[0-9]{8}$/,
    flag: "🇳🇮",
    dialing_code: "+505",
    maxDigits: 9,
    continent: "North America",
  },
  {
    code: "NE",
    name: "Niger",
    pattern: /^\+227[0-9]{8}$/,
    flag: "🇳🇪",
    dialing_code: "+227",
    maxDigits: 9,
    continent: "Africa",
  },
  {
    code: "NG",
    name: "Nigeria",
    pattern: /^\+234[0-9]{10}$/,
    flag: "🇳🇬",
    dialing_code: "+234",
    maxDigits: 10,
    continent: "Africa",
  },
  {
    code: "NU",
    name: "Niue",
    pattern: /^\+683[0-9]{4}$/,
    flag: "🇳🇺",
    dialing_code: "+683",
    maxDigits: 9,
    continent: "Oceania",
  },
  {
    code: "NF",
    name: "Norfolk Island",
    pattern: /^\+672[0-2][0-9]{3}$/,
    flag: "🇳🇫",
    dialing_code: "+672",
    maxDigits: 9,
    continent: "Oceania",
  },
  {
    code: "MP",
    name: "Northern Mariana Islands",
    pattern: /^\+1[670][0-9]{7}$/,
    flag: "🇲🇵",
    dialing_code: "+1-670",
    maxDigits: 9,
    continent: "Oceania",
  },
  {
    code: "NO",
    name: "Norway",
    pattern: /^\+47[0-9]{8}$/,
    flag: "🇳🇴",
    dialing_code: "+47",
    maxDigits: 9,
    continent: "Europe",
  },
  {
    code: "OM",
    name: "Oman",
    pattern: /^\+968[0-9]{8}$/,
    flag: "🇴🇲",
    dialing_code: "+968",
    maxDigits: 9,
    continent: "Asia",
  },
  {
    code: "PK",
    name: "Pakistan",
    pattern: /^\+92[0-9]{10}$/,
    flag: "🇵🇰",
    dialing_code: "+92",
    maxDigits: 10,
    continent: "Asia",
  },
  {
    code: "PW",
    name: "Palau",
    pattern: /^\+680[0-9]{7}$/,
    flag: "🇵🇼",
    dialing_code: "+680",
    maxDigits: 9,
    continent: "Oceania",
  },
  {
    code: "PA",
    name: "Panama",
    pattern: /^\+507[0-9]{7}$/,
    flag: "🇵🇦",
    dialing_code: "+507",
    maxDigits: 9,
    continent: "North America",
  },
  {
    code: "PG",
    name: "Papua New Guinea",
    pattern: /^\+675[0-9]{9}$/,
    flag: "🇵🇬",
    dialing_code: "+675",
    maxDigits: 9,
    continent: "Oceania",
  },
  {
    code: "PY",
    name: "Paraguay",
    pattern: /^\+595[0-9]{9}$/,
    flag: "🇵🇾",
    dialing_code: "+595",
    maxDigits: 9,
    continent: "South America",
  },
  {
    code: "PE",
    name: "Peru",
    pattern: /^\+51[0-9]{9}$/,
    flag: "🇵🇪",
    dialing_code: "+51",
    maxDigits: 9,
    continent: "South America",
  },
  {
    code: "PH",
    name: "Philippines",
    pattern: /^\+63[0-9]{10}$/,
    flag: "🇵🇭",
    dialing_code: "+63",
    maxDigits: 10,
    continent: "Asia",
  },
  {
    code: "PL",
    name: "Poland",
    pattern: /^\+48[0-9]{9}$/,
    flag: "🇵🇱",
    dialing_code: "+48",
    maxDigits: 9,
    continent: "Europe",
  },
  {
    code: "PT",
    name: "Portugal",
    pattern: /^\+351[0-9]{9}$/,
    flag: "🇵🇹",
    dialing_code: "+351",
    maxDigits: 9,
    continent: "Europe",
  },
  {
    code: "PR",
    name: "Puerto Rico",
    pattern: /^\+1[787|939][0-9]{7}$/,
    flag: "🇵🇷",
    dialing_code: "+1-787",
    maxDigits: 9,
    continent: "North America",
  },
  {
    code: "QA",
    name: "Qatar",
    pattern: /^\+974[0-9]{8}$/,
    flag: "🇶🇦",
    dialing_code: "+974",
    maxDigits: 9,
    continent: "MiddleEast",
  },
  {
    code: "RE",
    name: "Réunion",
    pattern: /^\+262[0-9]{9}$/,
    flag: "🇷🇪",
    dialing_code: "+262",
    maxDigits: 9,
    continent: "Africa",
  },
  {
    code: "RO",
    name: "Romania",
    pattern: /^\+40[0-9]{10}$/,
    flag: "🇷🇴",
    dialing_code: "+40",
    maxDigits: 10,
    continent: "Europe",
  },
  {
    code: "RU",
    name: "Russia",
    pattern: /^\+7[0-9]{10}$/,
    flag: "🇷🇺",
    dialing_code: "+7",
    maxDigits: 10,
    continent: "Europe",
  },
  {
    code: "RW",
    name: "Rwanda",
    pattern: /^\+250[0-9]{9}$/,
    flag: "🇷🇼",
    dialing_code: "+250",
    maxDigits: 10,
    continent: "Africa",
  },
  {
    code: "BL",
    name: "Saint Barthélemy",
    pattern: /^\+590[0-9]{9}$/,
    flag: "🇲🇶",
    dialing_code: "+590",
    maxDigits: 10,
    continent: "North America",
  },
  {
    code: "SH",
    name: "Saint Helena",
    pattern: /^\+290[0-9]{4}$/,
    flag: "🇱🇸",
    dialing_code: "+290",
    maxDigits: 10,
    continent: "Africa",
  },
  {
    code: "KN",
    name: "Saint Kitts and Nevis",
    pattern: /^\+1[869][0-9]{7}$/,
    flag: "🇰🇳",
    dialing_code: "+1-869",
    maxDigits: 10,
    continent: "North America",
  },
  {
    code: "LC",
    name: "Saint Lucia",
    pattern: /^\+1[758][0-9]{7}$/,
    flag: "🇱🇨",
    dialing_code: "+1-758",
    maxDigits: 10,
    continent: "North America",
  },
  {
    code: "PM",
    name: "Saint Pierre and Miquelon",
    pattern: /^\+508[0-9]{6}$/,
    flag: "🇵🇲",
    dialing_code: "+508",
    maxDigits: 10,
    continent: "North America",
  },
  {
    code: "VC",
    name: "Saint Vincent and the Grenadines",
    pattern: /^\+1[784][0-9]{7}$/,
    flag: "🇻🇨",
    dialing_code: "+1-784",
    maxDigits: 10,
    continent: "North America",
  },
  {
    code: "WS",
    name: "Samoa",
    pattern: /^\+685[0-9]{5}$/,
    flag: "🇼🇸",
    dialing_code: "+685",
    maxDigits: 9,
    continent: "Oceania",
  },
  {
    code: "SM",
    name: "San Marino",
    pattern: /^\+378[0-9]{7}$/,
    flag: "🇸🇲",
    dialing_code: "+378",
    maxDigits: 9,
    continent: "Europe",
  },
  {
    code: "ST",
    name: "São Tomé and Príncipe",
    pattern: /^\+239[0-9]{7}$/,
    flag: "🇸🇹",
    dialing_code: "+239",
    maxDigits: 9,
    continent: "Africa",
  },
  {
    code: "SA",
    name: "Saudi Arabia",
    pattern: /^\+966[0-9]{9}$/,
    flag: "🇸🇦",
    dialing_code: "+966",
    maxDigits: 9,
    continent: "Asia",
  },
  {
    code: "SN",
    name: "Senegal",
    pattern: /^\+221[0-9]{9}$/,
    flag: "🇸🇳",
    dialing_code: "+221",
    maxDigits: 9,
    continent: "Africa",
  },
  {
    code: "RS",
    name: "Serbia",
    pattern: /^\+381[0-9]{8,9}$/,
    flag: "🇷🇸",
    dialing_code: "+381",
    maxDigits: 10,
    continent: "Europe",
  },
  {
    code: "SC",
    name: "Seychelles",
    pattern: /^\+248[0-9]{7}$/,
    flag: "🇸🇨",
    dialing_code: "+248",
    maxDigits: 9,
    continent: "Africa",
  },
  {
    code: "SL",
    name: "Sierra Leone",
    pattern: /^\+232[0-9]{8}$/,
    flag: "🇸🇱",
    dialing_code: "+232",
    maxDigits: 9,
    continent: "Africa",
  },
  {
    code: "SG",
    name: "Singapore",
    pattern: /^\+65[0-9]{8}$/,
    flag: "🇸🇬",
    dialing_code: "+65",
    maxDigits: 8,
    continent: "Asia",
  },
  {
    code: "SX",
    name: "Sint Maarten",
    pattern: /^\+1[721][0-9]{7}$/,
    flag: "🇸🇽",
    dialing_code: "+1-721",
    maxDigits: 10,
    continent: "North America",
  },
  {
    code: "SK",
    name: "Slovakia",
    pattern: /^\+421[0-9]{9}$/,
    flag: "🇸🇰",
    dialing_code: "+421",
    maxDigits: 9,
    continent: "Europe",
  },
  {
    code: "SI",
    name: "Slovenia",
    pattern: /^\+386[0-9]{8}$/,
    flag: "🇸🇮",
    dialing_code: "+386",
    maxDigits: 9,
    continent: "Europe",
  },
  {
    code: "SB",
    name: "Solomon Islands",
    pattern: /^\+677[0-9]{4}$/,
    flag: "🇸🇧",
    dialing_code: "+677",
    maxDigits: 9,
    continent: "Oceania",
  },
  {
    code: "SO",
    name: "Somalia",
    pattern: /^\+252[0-9]{7}$/,
    flag: "🇸🇴",
    dialing_code: "+252",
    maxDigits: 9,
    continent: "Africa",
  },
  {
    code: "ZA",
    name: "South Africa",
    pattern: /^\+27[0-9]{9}$/,
    flag: "🇿🇦",
    dialing_code: "+27",
    maxDigits: 9,
    continent: "Africa",
  },
  {
    code: "GS",
    name: "South Georgia and the South Sandwich Islands",
    pattern: /^\+500[0-9]{4}$/,
    flag: "🇬🇸",
    dialing_code: "+500",
    maxDigits: 9,
    continent: "South America",
  },
  {
    code: "SS",
    name: "South Sudan",
    pattern: /^\+211[0-9]{8}$/,
    flag: "🇸🇸",
    dialing_code: "+211",
    maxDigits: 9,
    continent: "Africa",
  },
  {
    code: "ES",
    name: "Spain",
    pattern: /^\+34[0-9]{9}$/,
    flag: "🇪🇸",
    dialing_code: "+34",
    maxDigits: 9,
    continent: "Europe",
  },
  {
    code: "LK",
    name: "Sri Lanka",
    pattern: /^\+94[0-9]{9}$/,
    flag: "🇱🇰",
    dialing_code: "+94",
    maxDigits: 9,
    continent: "Asia",
  },
  {
    code: "SD",
    name: "Sudan",
    pattern: /^\+249[0-9]{9}$/,
    flag: "🇸🇩",
    dialing_code: "+249",
    maxDigits: 9,
    continent: "Africa",
  },
  {
    code: "SR",
    name: "Suriname",
    pattern: /^\+597[0-9]{7}$/,
    flag: "🇸🇷",
    dialing_code: "+597",
    maxDigits: 9,
    continent: "South America",
  },
  {
    code: "SE",
    name: "Sweden",
    pattern: /^\+46[0-9]{8,9}$/,
    flag: "🇸🇪",
    dialing_code: "+46",
    maxDigits: 10,
    continent: "Europe",
  },
  {
    code: "CH",
    name: "Switzerland",
    pattern: /^\+41[0-9]{7,9}$/,
    flag: "🇨🇭",
    dialing_code: "+41",
    maxDigits: 10,
    continent: "Europe",
  },
  {
    code: "SY",
    name: "Syria",
    pattern: /^\+963[0-9]{8}$/,
    flag: "🇸🇾",
    dialing_code: "+963",
    maxDigits: 9,
    continent: "MiddleEast",
  },
  {
    code: "TW",
    name: "Taiwan",
    pattern: /^\+886[0-9]{9}$/,
    flag: "🇹🇼",
    dialing_code: "+886",
    maxDigits: 9,
    continent: "Asia",
  },
  {
    code: "TJ",
    name: "Tajikistan",
    pattern: /^\+992[0-9]{7}$/,
    flag: "🇹🇯",
    dialing_code: "+992",
    maxDigits: 9,
    continent: "Asia",
  },
  {
    code: "TZ",
    name: "Tanzania",
    pattern: /^\+255[0-9]{9}$/,
    flag: "🇹🇿",
    dialing_code: "+255",
    maxDigits: 9,
    continent: "Africa",
  },
  {
    code: "TH",
    name: "Thailand",
    pattern: /^\+66[0-9]{9}$/,
    flag: "🇹🇭",
    dialing_code: "+66",
    maxDigits: 9,
    continent: "Asia",
  },
  {
    code: "TG",
    name: "Togo",
    pattern: /^\+228[0-9]{7}$/,
    flag: "🇹🇬",
    dialing_code: "+228",
    maxDigits: 9,
    continent: "Africa",
  },
  {
    code: "TK",
    name: "Tokelau",
    pattern: /^\+690[0-9]{4}$/,
    flag: "🇹🇰",
    dialing_code: "+690",
    maxDigits: 9,
    continent: "Oceania",
  },
  {
    code: "TO",
    name: "Tonga",
    pattern: /^\+676[0-9]{5}$/,
    flag: "🇹🇴",
    dialing_code: "+676",
    maxDigits: 9,
    continent: "Oceania",
  },
  {
    code: "TT",
    name: "Trinidad and Tobago",
    pattern: /^\+1[868][0-9]{7}$/,
    flag: "🇹🇹",
    dialing_code: "+1-868",
    maxDigits: 10,
    continent: "North America",
  },
  {
    code: "TN",
    name: "Tunisia",
    pattern: /^\+216[0-9]{8}$/,
    flag: "🇹🇳",
    dialing_code: "+216",
    maxDigits: 8,
    continent: "Africa",
  },
  {
    code: "TR",
    name: "Turkey",
    pattern: /^\+90[0-9]{10}$/,
    flag: "🇹🇷",
    dialing_code: "+90",
    maxDigits: 10,
    continent: "Asia",
  },
  {
    code: "TM",
    name: "Turkmenistan",
    pattern: /^\+993[0-9]{8}$/,
    flag: "🇹🇲",
    dialing_code: "+993",
    maxDigits: 9,
    continent: "Asia",
  },
  {
    code: "TC",
    name: "Turks and Caicos Islands",
    pattern: /^\+1[649][0-9]{7}$/,
    flag: "🇹🇨",
    dialing_code: "+1-649",
    maxDigits: 10,
    continent: "North America",
  },
  {
    code: "TV",
    name: "Tuvalu",
    pattern: /^\+688[0-9]{4}$/,
    flag: "🇹🇻",
    dialing_code: "+688",
    maxDigits: 9,
    continent: "Oceania",
  },
  {
    code: "UG",
    name: "Uganda",
    pattern: /^\+256[0-9]{9}$/,
    flag: "🇺🇬",
    dialing_code: "+256",
    maxDigits: 9,
    continent: "Africa",
  },
  {
    code: "UA",
    name: "Ukraine",
    pattern: /^\+380[0-9]{9}$/,
    flag: "🇺🇦",
    dialing_code: "+380",
    maxDigits: 9,
    continent: "Europe",
  },
  {
    code: "AE",
    name: "United Arab Emirates",
    pattern: /^\+971[0-9]{9}$/,
    flag: "🇦🇪",
    dialing_code: "+971",
    maxDigits: 9,
    continent: "MiddleEast",
  },
  {
    code: "GB",
    name: "United Kingdom",
    pattern: /^\+44[0-9]{10}$/,
    flag: "🇬🇧",
    dialing_code: "+44",
    maxDigits: 10,
    continent: "Europe",
  },
  {
    code: "US",
    name: "United States",
    pattern: /^\+1[0-9]{10}$/,
    flag: "🇺🇸",
    dialing_code: "+1",
    maxDigits: 10,
    continent: "North America",
  },
  {
    code: "UY",
    name: "Uruguay",
    pattern: /^\+598[0-9]{8}$/,
    flag: "🇺🇾",
    dialing_code: "+598",
    maxDigits: 9,
    continent: "South America",
  },
  {
    code: "UZ",
    name: "Uzbekistan",
    pattern: /^\+998[0-9]{8}$/,
    flag: "🇺🇿",
    dialing_code: "+998",
    maxDigits: 9,
    continent: "Asia",
  },
  {
    code: "VU",
    name: "Vanuatu",
    pattern: /^\+678[0-9]{4}$/,
    flag: "🇻🇺",
    dialing_code: "+678",
    maxDigits: 9,
    continent: "Oceania",
  },
  {
    code: "VA",
    name: "Vatican City",
    pattern: /^\+379[0-9]{5}$/,
    flag: "🇻🇦",
    dialing_code: "+379",
    maxDigits: 9,
    continent: "Europe",
  },
  {
    code: "VE",
    name: "Venezuela",
    pattern: /^\+58[0-9]{10}$/,
    flag: "🇻🇪",
    dialing_code: "+58",
    maxDigits: 11,
    continent: "South America",
  },
  {
    code: "VN",
    name: "Vietnam",
    pattern: /^\+84[0-9]{9}$/,
    flag: "🇻🇳",
    dialing_code: "+84",
    maxDigits: 9,
    continent: "Asia",
  },
  {
    code: "WF",
    name: "Wallis and Futuna",
    pattern: /^\+681[0-9]{4}$/,
    flag: "🇼🇫",
    dialing_code: "+681",
    maxDigits: 9,
    continent: "Oceania",
  },
  {
    code: "YE",
    name: "Yemen",
    pattern: /^\+967[0-9]{9}$/,
    flag: "🇾🇪",
    dialing_code: "+967",
    maxDigits: 9,
    continent: "MiddleEast",
  },
  {
    code: "ZM",
    name: "Zambia",
    pattern: /^\+260[0-9]{9}$/,
    flag: "🇿🇲",
    dialing_code: "+260",
    maxDigits: 9,
    continent: "Africa",
  },
  {
    code: "ZW",
    name: "Zimbabwe",
    pattern: /^\+263[0-9]{9}$/,
    flag: "🇿🇼",
    dialing_code: "+263",
    maxDigits: 9,
    continent: "Africa",
  },
];

export type { CountryPhonePattern };
