const countryStateData: { [key: string]: string[] } = {
  Afghanistan: [
    "Badakhshan",
    "Badghis",
    "Baghlan",
    "Balkh",
    "Bamyan",
    "Daykundi",
    "Farah",
    "Faryab",
    "Ghazni",
    "Ghor",
    "Helmand",
    "Herat",
    "Jowzjan",
    "Kabul",
    "Kandahar",
    "Kapisa",
    "Khost",
    "Kunar",
    "Kunduz",
    "Laghman",
    "Logar",
    "Nangarhar",
    "Nimruz",
    "Nuristan",
    "Paktia",
    "Paktika",
    "Panjshir",
    "Parwan",
    "Samangan",
    "Sar-e Pol",
    "Takhar",
    "Urozgan",
    "Zabul",
  ],
  Albania: [
    "Berat",
    "Dibër",
    "Durrës",
    "Elbasan",
    "Fier",
    "Gjirokastër",
    "Korçë",
    "Kukës",
    "Lezhë",
    "Shkodër",
    "Tiranë",
    "Vlorë",
  ],
  Algeria: [
    "Adrar",
    "Ain Defla",
    "Ain Temouchent",
    "Algiers",
    "Annaba",
    "Batna",
    "Bechar",
    "Bejaia",
    "Biskra",
    "Blida",
    "Bordj Bou Arreridj",
    "Bouira",
    "Boumerdes",
    "Chlef",
    "Constantine",
    "Djelfa",
    "El Bayadh",
    "El Oued",
    "El Tarf",
    "Ghardaia",
    "Guelma",
    "Illizi",
    "Jijel",
    "Khenchela",
    "Laghouat",
    "Mascara",
    "Medea",
    "Mila",
    "Mostaganem",
    "M'Sila",
    "Naama",
    "Oran",
    "Ouargla",
    "Oum el Bouaghi",
    "Relizane",
    "Saida",
    "Setif",
    "Sidi Bel Abbes",
    "Skikda",
    "Souk Ahras",
    "Tamanrasset",
    "Tebessa",
    "Tiaret",
    "Tindouf",
    "Tipaza",
    "Tissemsilt",
    "Tizi Ouzou",
    "Tlemcen",
  ],
  Andorra: [
    "Andorra la Vella",
    "Canillo",
    "Encamp",
    "Escaldes-Engordany",
    "La Massana",
    "Ordino",
    "Sant Julià de Lòria",
  ],
  Angola: [
    "Bengo",
    "Benguela",
    "Bié",
    "Cabinda",
    "Cuando Cubango",
    "Cuanza Norte",
    "Cuanza Sul",
    "Cunene",
    "Huambo",
    "Huíla",
    "Luanda",
    "Lunda Norte",
    "Lunda Sul",
    "Malanje",
    "Moxico",
    "Namibe",
    "Uíge",
    "Zaire",
  ],
  Argentina: [
    "Buenos Aires",
    "Catamarca",
    "Chaco",
    "Chubut",
    "Córdoba",
    "Corrientes",
    "Entre Ríos",
    "Formosa",
    "Jujuy",
    "La Pampa",
    "La Rioja",
    "Mendoza",
    "Misiones",
    "Neuquén",
    "Río Negro",
    "Salta",
    "San Juan",
    "San Luis",
    "Santa Cruz",
    "Santa Fe",
    "Santiago del Estero",
    "Tierra del Fuego",
    "Tucumán",
  ],
  Armenia: [
    "Aragatsotn",
    "Ararat",
    "Armavir",
    "Gegharkunik",
    "Kotayk",
    "Lori",
    "Shirak",
    "Syunik",
    "Tavush",
    "Vayots Dzor",
    "Yerevan",
  ],
  Australia: [
    "Australian Capital Territory",
    "New South Wales",
    "Northern Territory",
    "Queensland",
    "South Australia",
    "Tasmania",
    "Victoria",
    "Western Australia",
  ],
  Austria: [
    "Burgenland",
    "Carinthia",
    "Lower Austria",
    "Upper Austria",
    "Salzburg",
    "Styria",
    "Tyrol",
    "Vienna",
    "Vorarlberg",
  ],
  Azerbaijan: [
    "Absheron",
    "Agdam",
    "Agdash",
    "Agjabadi",
    "Agstafa",
    "Agsu",
    "Astara",
    "Baku",
    "Balakan",
    "Barda",
    "Beylagan",
    "Bilasuvar",
    "Dashkasan",
    "Fuzuli",
    "Gadabay",
    "Ganja",
    "Goranboy",
    "Goychay",
    "Goygol",
    "Hajigabul",
    "Imishli",
    "Ismayilli",
    "Kalbajar",
    "Khachmaz",
    "Khankendi",
    "Khojali",
    "Khojavend",
    "Kurdamir",
    "Lachin",
    "Lankaran",
    "Lerik",
    "Masally",
    "Mingachevir",
    "Naftalan",
    "Nakhchivan",
    "Neftchala",
    "Oghuz",
    "Qabala",
    "Qakh",
    "Qazakh",
    "Quba",
    "Qubadli",
    "Qusar",
    "Saatly",
    "Sabirabad",
    "Shabran",
    "Shaki",
    "Salyan",
    "Shamakhi",
    "Shamkir",
    "Sharur",
    "Shirvan",
    "Shusha",
    "Siazan",
    "Sumqayit",
    "Tartar",
    "Tovuz",
    "Ujar",
    "Xaçmaz",
    "Xankandi",
    "Xızı",
    "Xocavənd",
    "Yardymli",
    "Yevlakh",
    "Zangilan",
    "Zaqatala",
    "Zardab",
  ],
  Bahrain: ["Capital", "Central", "Muharraq", "Northern", "Southern"],
  Bangladesh: [
    "Barisal",
    "Chittagong",
    "Dhaka",
    "Khulna",
    "Mymensingh",
    "Rajshahi",
    "Rangpur",
    "Sylhet",
  ],
  Belarus: [
    "Brest Region",
    "Gomel Region",
    "Grodno Region",
    "Minsk",
    "Minsk Region",
    "Mogilev Region",
    "Vitebsk Region",
  ],
  Belgium: [
    "Antwerp",
    "Brussels-Capital Region",
    "East Flanders",
    "Flemish Brabant",
    "Hainaut",
    "Liège",
    "Limburg",
    "Luxembourg",
    "Namur",
    "Walloon Brabant",
    "West Flanders",
  ],
  Belize: ["Belize", "Cayo", "Corozal", "Orange Walk", "Stann Creek", "Toledo"],
  Benin: [
    "Alibori",
    "Atakora",
    "Atlantique",
    "Borgou",
    "Collines",
    "Couffo",
    "Donga",
    "Littoral",
    "Mono",
    "Ouémé",
    "Plateau",
    "Zou",
  ],
  Bhutan: [
    "Bumthang",
    "Chukha",
    "Dagana",
    "Gasa",
    "Haa",
    "Lhuntse",
    "Mongar",
    "Paro",
    "Pemagatshel",
    "Punakha",
    "Samdrup Jongkhar",
    "Samtse",
    "Sarpang",
    "Thimphu",
    "Trashigang",
    "Trashiyangtse",
    "Trongsa",
    "Tsirang",
    "Wangdue Phodrang",
    "Zhemgang",
  ],
  Bolivia: [
    "Beni",
    "Chuquisaca",
    "Cochabamba",
    "La Paz",
    "Oruro",
    "Pando",
    "Potosí",
    "Santa Cruz",
    "Tarija",
  ],
  "Bosnia and Herzegovina": [
    "Bosnia and Herzegovina",
    "Federation of Bosnia and Herzegovina",
    "Republika Srpska",
  ],
  Botswana: [
    "Central",
    "Ghanzi",
    "Kgalagadi",
    "Kgatleng",
    "Kweneng",
    "North-East",
    "North-West",
    "South-East",
    "Southern",
  ],
  Brazil: [
    "Acre",
    "Alagoas",
    "Amapá",
    "Amazonas",
    "Bahia",
    "Ceará",
    "Distrito Federal",
    "Espírito Santo",
    "Goiás",
    "Maranhão",
    "Mato Grosso",
    "Mato Grosso do Sul",
    "Minas Gerais",
    "Pará",
    "Paraíba",
    "Paraná",
    "Pernambuco",
    "Piauí",
    "Rio de Janeiro",
    "Rio Grande do Norte",
    "Rio Grande do Sul",
    "Rondônia",
    "Roraima",
    "Santa Catarina",
    "São Paulo",
    "Sergipe",
    "Tocantins",
  ],
  Brunei: ["Belait", "Brunei-Muara", "Temburong", "Tutong"],
  Bulgaria: [
    "Blagoevgrad",
    "Burgas",
    "Dobrich",
    "Gabrovo",
    "Haskovo",
    "Kardzhali",
    "Kyustendil",
    "Lovech",
    "Montana",
    "Pazardzhik",
    "Pernik",
    "Pleven",
    "Plovdiv",
    "Razgrad",
    "Ruse",
    "Shumen",
    "Silistra",
    "Sliven",
    "Smolyan",
    "Sofia City",
    "Sofia Province",
    "Stara Zagora",
    "Targovishte",
    "Varna",
    "Veliko Tarnovo",
    "Vidin",
    "Vratsa",
    "Yambol",
  ],
  "Burkina Faso": [
    "Balé",
    "Bam",
    "Banhout",
    "Bazèga",
    "Bougouriba",
    "Boulgou",
    "Ganzourgou",
    "Gnagna",
    "Gourma",
    "Houet",
    "Ioba",
    "Kadiogo",
    "Kénédougou",
    "Komondjari",
    "Kompienga",
    "Kossi",
    "Koulpélogo",
    "Kouritenga",
    "Kourwéogo",
    "Léraba",
    "Loroum",
    "Mouhoun",
    "Nahouri",
    "Namentenga",
    "Naoum",
    "Oubritenga",
    "Oudalan",
    "Passoré",
    "Poni",
    "Sanguié",
    "Séno",
    "Sissili",
    "Soum",
    "Sourou",
    "Tapoa",
    "Tuy",
    "Yagha",
    "Yatenga",
    "Ziro",
    "Zondoma",
  ],
  Burundi: [
    "Bubanza",
    "Bujumbura Mairie",
    "Bujumbura Rural",
    "Bururi",
    "Cankuzo",
    "Cibitoke",
    "Gitega",
    "Karuzi",
    "Kayanza",
    "Kirundo",
    "Makamba",
    "Muramvya",
    "Mwaro",
    "Ngozi",
    "Rumonge",
    "Rutana",
    "Ruyigi",
  ],
  Cambodia: [
    "Banteay Meanchey",
    "Battambang",
    "Kampong Cham",
    "Kampong Chhnang",
    "Kampong Speu",
    "Kampong Thom",
    "Kampot",
    "Kandal",
    "Kep",
    "Koh Kong",
    "Kratie",
    "Mondulkiri",
    "Oddar Meanchey",
    "Pailin",
    "Phnom Penh",
    "Preah Vihear",
    "Pursat",
    "Ratanakiri",
    "Siem Reap",
    "Sihanoukville",
    "Stung Treng",
    "Svay Rieng",
    "Takeo",
  ],
  Cameroon: [
    "Adamawa",
    "Centre",
    "East",
    "Far North",
    "Littoral",
    "North",
    "Northwest",
    "South",
    "Southwest",
    "West",
  ],
  Canada: [
    "Alberta",
    "British Columbia",
    "Manitoba",
    "New Brunswick",
    "Newfoundland and Labrador",
    "Nova Scotia",
    "Ontario",
    "Prince Edward Island",
    "Quebec",
    "Saskatchewan",
    "Northwest Territories",
    "Nunavut",
    "Yukon",
  ],
  "Cape Verde": [
    "Boa Vista",
    "Brava",
    "Maio",
    "Mosteiros",
    "Paul",
    "Porto Novo",
    "Praia",
    "Ribeira Brava",
    "Ribeira Grande",
    "Sal",
    "Santa Catarina",
    "Santa Catarina do Fogo",
    "Santa Cruz",
    "São Domingos",
    "São Filipe",
    "São Lourenço dos Órgãos",
    "São Miguel",
    "São Nicolau",
    "Tarrafal",
    "Tarrafal de São Nicolau",
  ],
  "Central African Republic": [
    "Bamingui-Bangoran",
    "Bangui",
    "Basse-Kotto",
    "Haute-Kotto",
    "Haut-Mbomou",
    "Kémo",
    "Lobaye",
    "Mambéré-Kadéï",
    "Mbomou",
    "Nana-Grebizi",
    "Nana-Mambéré",
    "Ombella-M'Poko",
    "Ouaka",
    "Ouham",
    "Ouham-Pendé",
    "Sangha-Mbaéré",
    "Vakaga",
  ],
  Chad: [
    "Bahr el Gazel",
    "Batha",
    "Borkou",
    "Ennedi-Est",
    "Ennedi-Ouest",
    "Guéra",
    "Hadjer-Lamis",
    "Kanem",
    "Lac",
    "Logone Occidental",
    "Logone Oriental",
    "Mandoul",
    "Mayo-Kebbi Est",
    "Mayo-Kebbi Ouest",
    "Moyen-Chari",
    "Ouaddaï",
    "Salamat",
    "Sila",
    "Tandjilé",
    "Tibesti",
    "Ville de N'Djamena",
  ],
  Chile: [
    "Arica y Parinacota",
    "Tarapacá",
    "Antofagasta",
    "Atacama",
    "Coquimbo",
    "Valparaíso",
    "Región Metropolitana de Santiago",
    "Libertador General Bernardo O'Higgins",
    "Maule",
    "Ñuble",
    "Biobío",
    "Araucanía",
    "Los Ríos",
    "Los Lagos",
    "Aysén del General Carlos Ibáñez del Campo",
    "Magallanes y de la Antártica Chilena",
  ],
  China: [
    "Anhui",
    "Beijing",
    "Chongqing",
    "Fujian",
    "Gansu",
    "Guangdong",
    "Guangxi",
    "Guizhou",
    "Hainan",
    "Hebei",
    "Heilongjiang",
    "Henan",
    "Hong Kong",
    "Hubei",
    "Hunan",
    "Inner Mongolia",
    "Jiangsu",
    "Jiangxi",
    "Jilin",
    "Liaoning",
    "Macau",
    "Ningxia",
    "Qinghai",
    "Shaanxi",
    "Shandong",
    "Shanghai",
    "Shanxi",
    "Sichuan",
    "Taiwan",
    "Tianjin",
    "Tibet",
    "Xinjiang",
    "Yunnan",
    "Zhejiang",
  ],
  Colombia: [
    "Amazonas",
    "Antioquia",
    "Arauca",
    "Atlántico",
    "Bogotá",
    "Bolívar",
    "Boyacá",
    "Caldas",
    "Caquetá",
    "Casanare",
    "Cauca",
    "Cesar",
    "Chocó",
    "Córdoba",
    "Cundinamarca",
    "Guainía",
    "Guaviare",
    "Huila",
    "La Guajira",
    "Magdalena",
    "Meta",
    "Nariño",
    "Norte de Santander",
    "Putumayo",
    "Quindío",
    "Risaralda",
    "San Andrés y Providencia",
    "Santander",
    "Sucre",
    "Tolima",
    "Valle del Cauca",
    "Vaupés",
    "Vichada",
  ],
  Comoros: ["Anjouan", "Grande Comore", "Mohéli"],
  Congo: [
    "Bouenza",
    "Brazzaville",
    "Cuvette",
    "Cuvette-Ouest",
    "Kouilou",
    "Lékoumou",
    "Likouala",
    "Niari",
    "Plateaux",
    "Pointe-Noire",
    "Sangha",
  ],
  "Costa Rica": [
    "Alajuela",
    "Cartago",
    "Guanacaste",
    "Heredia",
    "Limón",
    "Puntarenas",
    "San José",
  ],
  Croatia: [
    "Bjelovar-Bilogora",
    "Brod-Posavina",
    "Dubrovnik-Neretva",
    "Istria",
    "Karlovac",
    "Koprivnica-Križevci",
    "Krapina-Zagorje",
    "Lika-Senj",
    "Međimurje",
    "Osijek-Baranja",
    "Požega-Slavonia",
    "Primorje-Gorski Kotar",
    "Šibenik-Knin",
    "Sisak-Moslavina",
    "Split-Dalmatia",
    "Varaždin",
    "Virovitica-Podravina",
    "Vukovar-Syrmia",
    "Zadar",
    "Zagreb",
  ],
  Cuba: [
    "Artemisa",
    "Camagüey",
    "Ciego de Ávila",
    "Cienfuegos",
    "Granma",
    "Guantánamo",
    "Holguín",
    "Isla de la Juventud",
    "La Habana",
    "Las Tunas",
    "Matanzas",
    "Mayabeque",
    "Pinar del Río",
    "Sancti Spíritus",
    "Santiago de Cuba",
    "Villa Clara",
  ],
  Cyprus: ["Famagusta", "Kyrenia", "Larnaca", "Limassol", "Nicosia", "Paphos"],
  "Czech Republic": [
    "Central Bohemia",
    "Hradec Králové",
    "Karlovy Vary",
    "Liberec",
    "Moravia-Silesia",
    "Olomouc",
    "Pardubice",
    "Plzeň",
    "South Bohemia",
    "South Moravia",
    "Ústí nad Labem",
    "Vysočina",
    "Zlín",
  ],
  Denmark: [
    "Capital Region of Denmark",
    "Central Denmark Region",
    "North Denmark Region",
    "Region Zealand",
    "South Denmark Region",
  ],
  Djibouti: ["Ali Sabieh", "Arta", "Dikhil", "Djibouti", "Obock", "Tadjourah"],
  Dominica: [
    "Saint Andrew Parish",
    "Saint David Parish",
    "Saint George Parish",
    "Saint John Parish",
    "Saint Joseph Parish",
    "Saint Luke Parish",
    "Saint Mark Parish",
    "Saint Patrick Parish",
    "Saint Paul Parish",
    "Saint Peter Parish",
  ],
  "Dominican Republic": [
    "Azua",
    "Baoruco",
    "Barahona",
    "Dajabón",
    "Distrito Nacional",
    "Duarte",
    "Elías Piña",
    "El Seibo",
    "Espaillat",
    "Hato Mayor",
    "Hermanas Mirabal",
    "Independencia",
    "La Altagracia",
    "La Romana",
    "La Vega",
    "María Trinidad Sánchez",
    "Monseñor Nouel",
    "Monte Cristi",
    "Monte Plata",
    "Pedernales",
    "Peravia",
    "Puerto Plata",
    "Samaná",
    "San Cristóbal",
    "San José de Ocoa",
    "San Juan",
    "San Pedro de Macorís",
    "Sánchez Ramírez",
    "Santiago",
    "Santiago Rodríguez",
    "Valverde",
  ],
  Ecuador: [
    "Azuay",
    "Bolívar",
    "Cañar",
    "Carchi",
    "Chimborazo",
    "Cotopaxi",
    "El Oro",
    "Esmeraldas",
    "Galápagos",
    "Guayas",
    "Imbabura",
    "Loja",
    "Los Ríos",
    "Manabí",
    "Morona Santiago",
    "Napo",
    "Orellana",
    "Pastaza",
    "Pichincha",
    "Santa Elena",
    "Santo Domingo de los Tsáchilas",
    "Sucumbíos",
    "Tungurahua",
    "Zamora Chinchipe",
  ],
  Egypt: [
    "Alexandria",
    "Aswan",
    "Asyut",
    "Beheira",
    "Beni Suef",
    "Cairo",
    "Dakahlia",
    "Damietta",
    "Faiyum",
    "Gharbia",
    "Giza",
    "Ismailia",
    "Kafr el-Sheikh",
    "Luxor",
    "Matrouh",
    "Minya",
    "Monufia",
    "New Valley",
    "North Sinai",
    "Port Said",
    "Qalyubia",
    "Qena",
    "Red Sea",
    "Sharqia",
    "Sohag",
    "South Sinai",
    "Suez",
  ],
  "El Salvador": [
    "Ahuachapán",
    "Cabañas",
    "Chalatenango",
    "Cuscatlán",
    "La Libertad",
    "La Paz",
    "La Unión",
    "Morazán",
    "San Miguel",
    "San Salvador",
    "San Vicente",
    "Santa Ana",
    "Sonsonate",
    "Usulután",
  ],
  "Equatorial Guinea": [
    "Annobón",
    "Bioko Norte",
    "Bioko Sur",
    "Centro Sur",
    "Kié-Ntem",
    "Litoral",
    "Wele-Nzas",
  ],
  Eritrea: [
    "Anseba",
    "Debub",
    "Gash-Barka",
    "Maekel",
    "Northern Red Sea",
    "Southern Red Sea",
  ],
  Estonia: [
    "Harju",
    "Hiiu",
    "Ida-Viru",
    "Järva",
    "Jõgeva",
    "Lääne",
    "Lääne-Viru",
    "Põlva",
    "Pärnu",
    "Rapla",
    "Saare",
    "Tartu",
    "Valga",
    "Viljandi",
    "Võru",
  ],
  Eswatini: ["Hhohho", "Lubombo", "Manzini", "Shiselweni"],
  Ethiopia: [
    "Addis Ababa",
    "Afar",
    "Amhara",
    "Benishangul-Gumuz",
    "Dire Dawa",
    "Gambela",
    "Harari",
    "Oromia",
    "Somali",
    "South West Ethiopia Peoples' Region",
    "Southern Nations, Nationalities, and Peoples' Region",
    "Tigray",
  ],
  Fiji: [
    "Ba",
    "Bua",
    "Cakaudrove",
    "Kadavu",
    "Lau",
    "Lomaiviti",
    "Macuata",
    "Nadroga-Navosa",
    "Naitasiri",
    "Namosi",
    "Ra",
    "Rewa",
    "Serua",
    "Tailevu",
  ],
  Finland: [
    "Åland Islands",
    "Lapland",
    "North Karelia",
    "North Ostrobothnia",
    "North Savo",
    "Ostrobothnia",
    "Päijät-Häme",
    "Satakunta",
    "South Karelia",
    "South Ostrobothnia",
    "South Savo",
    "Tavastia Proper",
    "Uusimaa",
    "Varsinais-Suomi",
  ],
  France: [
    "Auvergne-Rhône-Alpes",
    "Bourgogne-Franche-Comté",
    "Brittany",
    "Centre-Val de Loire",
    "Corsica",
    "Grand Est",
    "Hauts-de-France",
    "Île-de-France",
    "Normandy",
    "Nouvelle-Aquitaine",
    "Occitanie",
    "Pays de la Loire",
    "Provence-Alpes-Côte d'Azur",
  ],
  Gabon: [
    "Estuaire",
    "Haut-Ogooué",
    "Moyen-Ogooué",
    "Ngounié",
    "Nyanga",
    "Ogooué-Ivindo",
    "Ogooué-Lolo",
    "Ogooué-Maritime",
    "Woleu-Ntem",
  ],
  Gambia: [
    "Central River",
    "Lower River",
    "North Bank",
    "Upper River",
    "West Coast",
    "Banjul",
  ],
  Georgia: [
    "Adjara",
    "Guria",
    "Imereti",
    "Kakheti",
    "Kvemo Kartli",
    "Mtskheta-Mtianeti",
    "Racha-Lechkhumi and Kvemo Svaneti",
    "Samegrelo-Zemo Svaneti",
    "Samtskhe-Javakheti",
    "Shida Kartli",
    "Tbilisi",
  ],
  Germany: [
    "Baden-Württemberg",
    "Bavaria",
    "Berlin",
    "Brandenburg",
    "Bremen",
    "Hamburg",
    "Hesse",
    "Lower Saxony",
    "Mecklenburg-Vorpommern",
    "North Rhine-Westphalia",
    "Rhineland-Palatinate",
    "Saarland",
    "Saxony",
    "Saxony-Anhalt",
    "Schleswig-Holstein",
    "Thuringia",
  ],
  Ghana: [
    "Ahafo",
    "Ashanti",
    "Bono",
    "Bono East",
    "Central",
    "Eastern",
    "Greater Accra",
    "North East",
    "Northern",
    "Oti",
    "Savannah",
    "Upper East",
    "Upper West",
    "Volta",
    "Western",
    "Western North",
  ],
  Greece: [
    "Attica",
    "Central Greece",
    "Central Macedonia",
    "Crete",
    "East Macedonia and Thrace",
    "Epirus",
    "Ionian Islands",
    "North Aegean",
    "Peloponnese",
    "South Aegean",
    "Thessaly",
    "West Greece",
    "West Macedonia",
  ],
  Grenada: [
    "Saint Andrew",
    "Saint David",
    "Saint George",
    "Saint John",
    "Saint Mark",
    "Saint Patrick",
    "Southern Grenadine Islands",
  ],
  Guatemala: [
    "Alta Verapaz",
    "Baja Verapaz",
    "Chimaltenango",
    "Chiquimula",
    "El Progreso",
    "Escuintla",
    "Guatemala",
    "Huehuetenango",
    "Izabal",
    "Jalapa",
    "Jutiapa",
    "Petén",
    "Quetzaltenango",
    "Quiché",
    "Retalhuleu",
    "Sacatepéquez",
    "San Marcos",
    "Santa Rosa",
    "Sololá",
    "Suchitepéquez",
    "Totonicapán",
    "Zacapa",
  ],
  Guinea: [
    "Beyla",
    "Boffa",
    "Boké",
    "Conakry",
    "Coyah",
    "Dabola",
    "Dalaba",
    "Dinguiraye",
    "Faranah",
    "Forécariah",
    "Fria",
    "Gaoual",
    "Guéckédou",
    "Kankan",
    "Kérouané",
    "Kindia",
    "Kissidougou",
    "Koubia",
    "Koundara",
    "Kouroussa",
    "Labé",
    "Lélouma",
    "Lola",
    "Macenta",
    "Mali",
    "Mamou",
    "Mandiana",
    "Nzérékoré",
    "Pita",
    "Siguiri",
    "Télimélé",
    "Tougué",
    "Yomou",
  ],
  "Guinea-Bissau": [
    "Bafatá",
    "Biombo",
    "Bissau",
    "Bolama",
    "Cacheu",
    "Gabú",
    "Oio",
    "Quinara",
    "Tombali",
    "Ilhas Bijagós",
  ],
  Guyana: [
    "Barima-Waini",
    "Cuyuni-Mazaruni",
    "Demerara-Mahaica",
    "East Berbice-Corentyne",
    "Essequibo Islands-West Demerara",
    "Mahaica-Berbice",
    "Pomeroon-Supenaam",
    "Potaro-Siparuni",
    "Upper Demerara-Berbice",
    "Upper Takutu-Upper Essequibo",
  ],
  Haiti: [
    "Artibonite",
    "Centre",
    "Grand'Anse",
    "Nippes",
    "Nord",
    "Nord-Est",
    "Nord-Ouest",
    "Ouest",
    "Sud",
    "Sud-Est",
  ],
  Honduras: [
    "Atlántida",
    "Colón",
    "Comayagua",
    "Copán",
    "Cortés",
    "Choluteca",
    "El Paraíso",
    "Francisco Morazán",
    "Gracias a Dios",
    "Intibucá",
    "Islas de la Bahía",
    "La Paz",
    "Lempira",
    "Ocotepeque",
    "Olancho",
    "Santa Bárbara",
    "Valle",
    "Yoro",
  ],
  Hungary: [
    "Bács-Kiskun",
    "Baranya",
    "Békés",
    "Borsod-Abaúj-Zemplén",
    "Csongrád-Csanád",
    "Fejér",
    "Győr-Moson-Sopron",
    "Hajdú-Bihar",
    "Heves",
    "Jász-Nagykun-Szolnok",
    "Komárom-Esztergom",
    "Nógrád",
    "Pest",
    "Somogy",
    "Szabolcs-Szatmár-Bereg",
    "Tolna",
    "Vas",
    "Veszprém",
    "Zala",
  ],
  Iceland: [
    "Capital Region",
    "Southern Peninsula",
    "Western Region",
    "Westfjords",
    "Northwest Region",
    "Northeast Region",
    "Eastern Region",
    "Southern Region",
  ],
  India: [
    "Andaman and Nicobar Islands",
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chandigarh",
    "Chhattisgarh",
    "Dadra and Nagar Haveli and Daman and Diu",
    "Delhi",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jammu and Kashmir",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Ladakh",
    "Lakshadweep",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Puducherry",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
  ],
  Indonesia: [
    "Aceh",
    "Bali",
    "Bangka Belitung Islands",
    "Banten",
    "Bengkulu",
    "Central Java",
    "Central Kalimantan",
    "Central Sulawesi",
    "East Java",
    "East Kalimantan",
    "East Nusa Tenggara",
    "Gorontalo",
    "Jakarta",
    "Jambi",
    "Lampung",
    "Maluku",
    "North Kalimantan",
    "North Maluku",
    "North Sulawesi",
    "North Sumatra",
    "Papua",
    "Riau",
    "Riau Islands",
    "Southeast Sulawesi",
    "South Kalimantan",
    "South Sulawesi",
    "South Sumatra",
    "West Java",
    "West Kalimantan",
    "West Nusa Tenggara",
    "West Papua",
    "West Sulawesi",
    "Yogyakarta",
  ],
  Iran: [
    "Alborz",
    "Ardabil",
    "Azerbaijan, East",
    "Azerbaijan, West",
    "Bushehr",
    "Chahar Mahall and Bakhtiari",
    "Fars",
    "Gilan",
    "Golestan",
    "Hamadan",
    "Hormozgan",
    "Ilam",
    "Isfahan",
    "Kerman",
    "Kermanshah",
    "Khuzestan",
    "Kohgiluyeh and Boyer-Ahmad",
    "Kurdistan",
    "Lorestan",
    "Markazi",
    "Mazandaran",
    "North Khorasan",
    "Qazvin",
    "Qom",
    "Razavi Khorasan",
    "Semnan",
    "Sistan and Baluchestan",
    "South Khorasan",
    "Tehran",
    "Yazd",
    "Zanjan",
  ],
  Iraq: [
    "Al Anbar",
    "Al Muthanna",
    "Al Qadisiyyah",
    "Babylon",
    "Baghdad",
    "Basra",
    "Dhi Qar",
    "Diyala",
    "Dohuk",
    "Erbil",
    "Karbala",
    "Kirkuk",
    "Maysan",
    "Najaf",
    "Nineveh",
    "Saladin",
    "Sulaymaniyah",
    "Wasit",
  ],
  Ireland: [
    "Carlow",
    "Cavan",
    "Clare",
    "Cork",
    "Donegal",
    "Dublin",
    "Galway",
    "Kerry",
    "Kildare",
    "Kilkenny",
    "Laois",
    "Leitrim",
    "Limerick",
    "Longford",
    "Louth",
    "Mayo",
    "Meath",
    "Monaghan",
    "Offaly",
    "Roscommon",
    "Sligo",
    "Tipperary",
    "Waterford",
    "Westmeath",
    "Wexford",
    "Wicklow",
  ],
  Israel: [
    "Central District",
    "Haifa District",
    "Jerusalem District",
    "Northern District",
    "Southern District",
    "Tel Aviv District",
  ],
  Italy: [
    "Abruzzo",
    "Aosta Valley",
    "Apulia",
    "Basilicata",
    "Calabria",
    "Campania",
    "Emilia-Romagna",
    "Friuli Venezia Giulia",
    "Lazio",
    "Liguria",
    "Lombardy",
    "Marche",
    "Molise",
    "Piedmont",
    "Sardinia",
    "Sicily",
    "Trentino-Alto Adige/Südtirol",
    "Tuscany",
    "Umbria",
    "Veneto",
  ],
  Jamaica: [
    "Clarendon",
    "Hanover",
    "Kingston",
    "Manchester",
    "Portland",
    "Saint Andrew",
    "Saint Ann",
    "Saint Catherine",
    "Saint Elizabeth",
    "Saint James",
    "Saint Mary",
    "Saint Thomas",
    "Trelawny",
    "Westmoreland",
  ],
  Japan: [
    "Aichi",
    "Akita",
    "Aomori",
    "Chiba",
    "Ehime",
    "Fukui",
    "Fukuoka",
    "Fukushima",
    "Gifu",
    "Gunma",
    "Hiroshima",
    "Hokkaido",
    "Hyogo",
    "Ibaraki",
    "Ishikawa",
    "Iwate",
    "Kagawa",
    "Kagoshima",
    "Kanagawa",
    "Kochi",
    "Kumamoto",
    "Kyoto",
    "Mie",
    "Miyagi",
    "Miyazaki",
    "Nagano",
    "Nagasaki",
    "Nara",
    "Niigata",
    "Oita",
    "Okayama",
    "Okinawa",
    "Osaka",
    "Saga",
    "Saitama",
    "Shiga",
    "Shimane",
    "Shizuoka",
    "Tochigi",
    "Tokushima",
    "Tokyo",
    "Tottori",
    "Toyama",
    "Wakayama",
    "Yamagata",
    "Yamaguchi",
    "Yamanashi",
  ],
  Jordan: [
    "Ajloun",
    "Aqaba",
    "Balqa",
    "Irbid",
    "Jerash",
    "Karak",
    "Maan",
    "Madaba",
    "Mafraq",
    "Tafilah",
    "Amman",
    "Zarqa",
  ],
  Kazakhstan: [
    "Akmola Region",
    "Aktobe Region",
    "Almaty",
    "Almaty Region",
    "Atyrau Region",
    "Baikonur",
    "East Kazakhstan Region",
    "Jambyl Region",
    "Karaganda Region",
    "Kostanay Region",
    "Kyzylorda Region",
    "Mangystau Region",
    "North Kazakhstan Region",
    "Nur-Sultan",
    "Pavlodar Region",
    "Shymkent",
    "Turkistan Region",
    "West Kazakhstan Region",
  ],
  Kenya: [
    "Baringo",
    "Bomet",
    "Bungoma",
    "Busia",
    "Elgeyo-Marakwet",
    "Embu",
    "Garissa",
    "Homa Bay",
    "Isiolo",
    "Kajiado",
    "Kakamega",
    "Kericho",
    "Kiambu",
    "Kilifi",
    "Kirinyaga",
    "Kisii",
    "Kisumu",
    "Kitui",
    "Kwale",
    "Laikipia",
    "Lamu",
    "Machakos",
    "Makueni",
    "Mandera",
    "Marsabit",
    "Meru",
    "Migori",
    "Mombasa",
    "Muranga",
    "Nairobi",
    "Nakuru",
    "Nandi",
    "Narok",
    "Nyamira",
    "Nyandarua",
    "Nyeri",
    "Samburu",
    "Siaya",
    "Taita-Taveta",
    "Tana River",
    "Tharaka-Nithi",
    "Trans-Nzoia",
    "Turkana",
    "Uasin Gishu",
    "Vihiga",
    "Wajir",
    "West Pokot",
  ],
  Kiribati: ["Banaba", "Gilbert Islands", "Line Islands"],
  Kosovo: [
    "Pristina",
    "Prizren",
    "Gjilan",
    "Peja",
    "Mitrovica",
    "Ferizaj",
    "Gjakova",
    "Podujevo",
    "Rahovec",
    "Kamenica",
    "Decan",
  ],
  Kuwait: [
    "Al Asimah",
    "Hawalli",
    "Al Farwaniyah",
    "Mubarak Al-Kabeer",
    "Al Jahra",
    "Ahmadi",
  ],
  Kyrgyzstan: [
    "Bishkek",
    "Batken",
    "Chuy",
    "Issyk-Kul",
    "Jalal-Abad",
    "Naryn",
    "Osh",
    "Talas",
  ],
  Laos: [
    "Attapeu",
    "Bokeo",
    "Bolikhamxai",
    "Champasak",
    "Houaphanh",
    "Khammouane",
    "Luang Namtha",
    "Luang Prabang",
    "Oudomxay",
    "Phongsaly",
    "Salavan",
    "Savannakhet",
    "Vientiane Prefecture",
    "Vientiane Province",
    "Xaignabouri",
    "Xaisomboun",
    "Xekong",
    "Xiangkhoang",
  ],
  Latvia: [
    "Aglona Municipality",
    "Aizkraukle Municipality",
    "Aluksne Municipality",
    "Augšdaugava Municipality",
    "Balvi Municipality",
    "Bauska Municipality",
    "Cēsis Municipality",
    "Dagda Municipality",
    "Dobele Municipality",
    "Gulbene Municipality",
    "Jekabpils Municipality",
    "Jelgava",
    "Jelgava Municipality",
    "Kraslava Municipality",
    "Kuldiga Municipality",
    "Limbazi Municipality",
    "Liepaja",
    "Livani Municipality",
    "Ludza Municipality",
    "Madona Municipality",
    "Ogre Municipality",
    "Preili Municipality",
    "Rezekne",
    "Rezekne Municipality",
    "Riga",
    "Salaspils Municipality",
    "Saldus Municipality",
    "Sigulda Municipality",
    "Smiltene Municipality",
    "South Kurzeme Municipality",
    "Talsi Municipality",
    "Tukums Municipality",
    "Valka Municipality",
    "Valmiera Municipality",
    "Ventspils",
    "Ventspils Municipality",
  ],
  Lebanon: [
    "Akkar",
    "Baalbek-Hermel",
    "Beirut",
    "Beqaa",
    "Mount Lebanon",
    "North",
    "Nabatieh",
    "South",
  ],
  Lesotho: [
    "Berea",
    "Butha-Buthe",
    "Leribe",
    "Mafeteng",
    "Maseru",
    "Mohale's Hoek",
    "Mokhotlong",
    "Qacha's Nek",
    "Quthing",
    "Thaba-Tseka",
  ],
  Liberia: [
    "Bomi",
    "Bong",
    "Gbarpolu",
    "Grand Bassa",
    "Grand Cape Mount",
    "Grand Gedeh",
    "Grand Kru",
    "Lofa",
    "Margibi",
    "Maryland",
    "Montserrado",
    "Nimba",
    "River Cess",
    "River Gee",
    "Sinoe",
  ],
  Libya: [
    "Al Butnan",
    "Al Jabal al Akhdar",
    "Al Jabal al Gharbi",
    "Al Jafara",
    "Al Jufra",
    "Al Kufra",
    "Al Marj",
    "Al Murgub",
    "An Nuqat al Khams",
    "Awbari",
    "Az Zawiyah",
    "Benghazi",
    "Derna",
    "Ghat",
    "Murzuq",
    "Misrata",
    "Nalut",
    "Sabha",
    "Sirte",
    "Wahat",
    "Wadi al Hayaa",
    "Tripoli",
  ],
  Liechtenstein: [
    "Balzers",
    "Eschen",
    "Gamprin",
    "Mauren",
    "Planken",
    "Ruggell",
    "Schaan",
    "Schellenberg",
    "Triesen",
    "Triesenberg",
    "Vaduz",
  ],
  Lithuania: [
    "Akmenė District Municipality",
    "Alytus City Municipality",
    "Alytus District Municipality",
    "Birštonas Municipality",
    "Biržai District Municipality",
    "Druskininkai Municipality",
    "Elektrėnai Municipality",
    "Ignalina District Municipality",
    "Jonava District Municipality",
    "Joniškis District Municipality",
    "Jurbarkas District Municipality",
    "Kaišiadorys District Municipality",
    "Kalvarija Municipality",
    "Kaunas City Municipality",
    "Kaunas District Municipality",
    "Kazlų Rūda Municipality",
    "Kėdainiai District Municipality",
    "Kelmė District Municipality",
    "Klaipėda City Municipality",
    "Klaipėda District Municipality",
    "Kretinga District Municipality",
    "Kupiškis District Municipality",
    "Lazdijai District Municipality",
    "Marijampolė Municipality",
    "Mažeikiai District Municipality",
    "Molėtai District Municipality",
    "Neringa Municipality",
    "Pakruojis District Municipality",
    "Palanga City Municipality",
    "Panevėžys City Municipality",
    "Panevėžys District Municipality",
    "Pasvalys District Municipality",
    "Plungė District Municipality",
    "Prienai District Municipality",
    "Radviliškis District Municipality",
    "Raseiniai District Municipality",
    "Rietavas Municipality",
    "Rokiškis District Municipality",
    "Šakiai District Municipality",
    "Šalčininkai District Municipality",
    "Šiauliai City Municipality",
    "Šiauliai District Municipality",
    "Šilalė District Municipality",
    "Šilutė District Municipality",
    "Širvintos District Municipality",
    "Skuodas District Municipality",
    "Tauragė District Municipality",
    "Telšiai District Municipality",
    "Trakai District Municipality",
    "Ukmergė District Municipality",
    "Utena District Municipality",
    "Varėna District Municipality",
    "Vilkaviškis District Municipality",
    "Vilnius City Municipality",
    "Vilnius District Municipality",
    "Zarasai District Municipality",
  ],
  Luxembourg: [
    "Canton of Capellen",
    "Canton of Clervaux",
    "Canton of Diekirch",
    "Canton of Echternach",
    "Canton of Esch-sur-Alzette",
    "Canton of Grevenmacher",
    "Canton of Luxembourg",
    "Canton of Mersch",
    "Canton of Redange",
    "Canton of Remich",
    "Canton of Vianden",
    "Canton of Wiltz",
  ],
  Madagascar: [
    "Antananarivo",
    "Antsiranana",
    "Fianarantsoa",
    "Mahajanga",
    "Toamasina",
    "Toliara",
  ],
  Malawi: [
    "Balaka",
    "Blantyre",
    "Chikwawa",
    "Chiradzulu",
    "Chitipa",
    "Dedza",
    "Dowa",
    "Karonga",
    "Kasungu",
    "Likoma",
    "Lilongwe",
    "Machinga",
    "Mangochi",
    "Mchinji",
    "Mulanje",
    "Mwanza",
    "Mzimba",
    "Neno",
    "Ntcheu",
    "Ntchisi",
    "Phalombe",
    "Rumphi",
    "Salima",
    "Thyolo",
    "Zomba",
  ],
  Malaysia: [
    "Johor",
    "Kedah",
    "Kelantan",
    "Kuala Lumpur",
    "Labuan",
    "Malacca",
    "Negeri Sembilan",
    "Pahang",
    "Penang",
    "Perak",
    "Perlis",
    "Putrajaya",
    "Sabah",
    "Sarawak",
    "Selangor",
    "Terengganu",
  ],
  Maldives: [
    "Alif Alif Atoll",
    "Alif Dhaal Atoll",
    "Baa Atoll",
    "Dhaalu Atoll",
    "Faafu Atoll",
    "Gaafu Alif Atoll",
    "Gaafu Dhaalu Atoll",
    "Gnaviyani Atoll",
    "Haa Alif Atoll",
    "Haa Dhaalu Atoll",
    "Kaafu Atoll",
    "Laamu Atoll",
    "Lhaviyani Atoll",
    "Male",
    "Meemu Atoll",
    "Noonu Atoll",
    "Raa Atoll",
    "Seenu Atoll",
    "Shaviyani Atoll",
    "Thaa Atoll",
    "Vaavu Atoll",
  ],
  Mali: [
    "Bamako",
    "Gao",
    "Kayes",
    "Kidal",
    "Koulikoro",
    "Ménaka",
    "Mopti",
    "Ségou",
    "Sikasso",
    "Taoudénit",
    "Tombouctou",
  ],
  Malta: [
    "Attard",
    "Balzan",
    "Birgu",
    "Birkirkara",
    "Birżebbuġa",
    "Cospicua",
    "Dingli",
    "Fgura",
    "Floriana",
    "Fontana",
    "Għajnsielem",
    "Għarb",
    "Għargħur",
    "Għasri",
    "Gzira",
    "Ħamrun",
    "Iklin",
    "Kalkara",
    "Kerċem",
    "Kirkop",
    "Lija",
    "Luqa",
    "Marsa",
    "Marsaskala",
    "Marsaxlokk",
    "Mdina",
    "Mellieħa",
    "Mġarr",
    "Mosta",
    "Mqabba",
    "Msida",
    "Mtarfa",
    "Nadur",
    "Naxxar",
    "Paola",
    "Pembroke",
    "Pietà",
    "Qala",
    "Qormi",
    "Qrendi",
    "Rabat",
    "Safi",
    "San Ġiljan",
    "San Ġwann",
    "San Lawrenz",
    "San Pawl il-Baħar",
    "Sannat",
    "Santa Luċija",
    "Santa Venera",
    "Siġġiewi",
    "Sliema",
    "Swieqi",
    "Ta' Xbiex",
    "Tarxien",
    "Valletta",
    "Victoria",
    "Xagħra",
    "Xewkija",
    "Xgħajra",
    "Żabbar",
    "Żebbuġ",
    "Żejtun",
    "Żurrieq",
  ],
  "Marshall Islands": [
    "Ailinglaplap",
    "Ailuk",
    "Arno",
    "Aur",
    "Ebon",
    "Enewetak",
    "Jabat",
    "Jaluit",
    "Kili",
    "Kwajalein",
    "Lae",
    "Lib",
    "Likiep",
    "Majuro",
    "Maloelap",
    "Mejit",
    "Mili",
    "Namorik",
    "Namu",
    "Rongelap",
    "Rongrik",
    "Toke",
    "Ujae",
    "Ujelang",
    "Utirik",
    "Wotho",
    "Wotje",
  ],
  Mauritania: [
    "Adrar",
    "Assaba",
    "Brakna",
    "Dakhlet Nouadhibou",
    "Gorgol",
    "Guidimaka",
    "Hodh Ech Chargui",
    "Hodh El Gharbi",
    "Inchiri",
    "Nouakchott-Nord",
    "Nouakchott-Ouest",
    "Nouakchott-Sud",
    "Tagant",
    "Tiris Zemmour",
    "Trarza",
  ],
  Mauritius: [
    "Black River",
    "Flacq",
    "Grand Port",
    "Moka",
    "Pamplemousses",
    "Plaines Wilhems",
    "Port Louis",
    "Rivière du Rempart",
    "Savanne",
    "Rodrigues",
    "Agalega Islands",
    "Cargados Carajos Shoals",
  ],
  Mexico: [
    "Aguascalientes",
    "Baja California",
    "Baja California Sur",
    "Campeche",
    "Chiapas",
    "Chihuahua",
    "Coahuila",
    "Colima",
    "Durango",
    "Guanajuato",
    "Guerrero",
    "Hidalgo",
    "Jalisco",
    "México",
    "Michoacán",
    "Morelos",
    "Nayarit",
    "Nuevo León",
    "Oaxaca",
    "Puebla",
    "Querétaro",
    "Quintana Roo",
    "San Luis Potosí",
    "Sinaloa",
    "Sonora",
    "Tabasco",
    "Tamaulipas",
    "Tlaxcala",
    "Veracruz",
    "Yucatán",
    "Zacatecas",
  ],
  Micronesia: ["Chuuk", "Kosrae", "Pohnpei", "Yap"],
  Moldova: [
    "Anenii Noi",
    "Bălți",
    "Basarabeasca",
    "Bender",
    "Briceni",
    "Cahul",
    "Călărași",
    "Cantemir",
    "Căușeni",
    "Chișinău",
    "Cimișlia",
    "Criuleni",
    "Dondușeni",
    "Drochia",
    "Dubăsari",
    "Edineț",
    "Fălești",
    "Florești",
    "Găgăuzia",
    "Glodeni",
    "Hîncești",
    "Ialoveni",
    "Leova",
    "Nisporeni",
    "Ocnița",
    "Orhei",
    "Rezina",
    "Rîșcani",
    "Sîngerei",
    "Soroca",
    "Șoldănești",
    "Ștefan Vodă",
    "Strășeni",
    "Taraclia",
    "Telenești",
    "Ungheni",
    "Transnistria",
  ],
  Monaco: ["La Condamine", "Monaco-Ville", "Monte Carlo", "Fontvieille"],
  Mongolia: [
    "Arkhangai",
    "Bayankhongor",
    "Bayan-Ölgii",
    "Darkhan-Uul",
    "Dornod",
    "Dornogovi",
    "Dundgovi",
    "Govi-Altai",
    "Govisümber",
    "Khentii",
    "Khovd",
    "Khövsgöl",
    "Ömnögovi",
    "Orkhon",
    "Selenge",
    "Sükhbaatar",
    "Töv",
    "Uvs",
    "Zavkhan",
    "Ulaanbaatar",
  ],
  Montenegro: [
    "Andrijevica",
    "Bar",
    "Berane",
    "Bijelo Polje",
    "Budva",
    "Danilovgrad",
    "Gusinje",
    "Herceg Novi",
    "Kolašin",
    "Kotor",
    "Mojkovac",
    "Nikšić",
    "Petnjica",
    "Plav",
    "Pljevlja",
    "Plužine",
    "Podgorica",
    "Rožaje",
    "Šavnik",
    "Tivat",
    "Ulcinj",
    "Zeta",
  ],
  Morocco: [
    "Agadir-Ida Ou Tanane",
    "Al Haouz",
    "Al Hoceïma",
    "Aousserd",
    "Assa-Zag",
    "Azilal",
    "Béni Mellal",
    "Benslimane",
    "Berkane",
    "Boujdour",
    "Boulemane",
    "Casablanca",
    "Chefchaouen",
    "Chichaoua",
    "Chtouka-Aït Baha",
    "Dakhla",
    "Drâa-Tafilalet",
    "El Hajeb",
    "El Jadida",
    "Errachidia",
    "Es Semara",
    "Essaouira",
    "Fahs-Anjra",
    "Fès",
    "Figuig",
    "Guelmim",
    "Guercif",
    "Ifrane",
    "Jerada",
    "Kénitra",
    "Khémisset",
    "Khénifra",
    "Khouribga",
    "Laâyoune",
    "Larache",
    "M'Diq-Fnideq",
    "Marrakech",
    "Médiouna",
    "Meknès",
    "Midelt",
    "Mohammadia",
    "Moulay Yacoub",
    "Nador",
    "Nouaceur",
    "Ouarzazate",
    "Oued Ed-Dahab",
    "Oujda-Angad",
    "Rehamna",
    "Safi",
    "Salé",
    "Sefrou",
    "Settat",
    "Sidi Bennour",
    "Sidi Ifni",
    "Sidi Kacem",
    "Sidi Slimane",
    "Skhirate-Témara",
    "Tan-Tan",
    "Tanger-Assilah",
    "Taounate",
    "Taourirt",
    "Tarfaya",
    "Tata",
    "Taza",
    "Tétouan",
    "Tinghir",
    "Tiznit",
    "Youssoufia",
    "Zagora",
  ],
  Mozambique: [
    "Cabo Delgado",
    "Gaza",
    "Inhambane",
    "Manica",
    "Maputo City",
    "Maputo Province",
    "Nampula",
    "Niassa",
    "Sofala",
    "Tete",
    "Zambézia",
  ],

  Myanmar: [
    "Ayeyarwady",
    "Bago",
    "Chin",
    "Kachin",
    "Kayah",
    "Kayin",
    "Magway",
    "Mandalay",
    "Mon",
    "Naypyidaw",
    "Rakhine",
    "Sagaing",
    "Shan",
    "Tanintharyi",
    "Yangon",
  ],
  Namibia: [
    "Erongo",
    "Hardap",
    "Karas",
    "Kavango East",
    "Kavango West",
    "Khomas",
    "Kunene",
    "Ohangwena",
    "Omaheke",
    "Omusati",
    "Oshana",
    "Oshikoto",
    "Otjozondjupa",
    "Zambezi",
  ],
  Nauru: [
    "Aiwo",
    "Anabar",
    "Anetan",
    "Anibare",
    "Baiti",
    "Boe",
    "Buada",
    "Denigomodu",
    "Ewa",
    "Ijuw",
    "Meneng",
    "Nibok",
    "Uaboe",
    "Yaren",
  ],
  Nepal: [
    "Bagmati",
    "Bheri",
    "Dhawalagiri",
    "Gandaki",
    "Janakpur",
    "Karnali",
    "Kosi",
    "Lumbini",
    "Mahakali",
    "Mechi",
    "Narayani",
    "Rapti",
    "Sagarmatha",
    "Seti",
  ],
  Netherlands: [
    "Drenthe",
    "Flevoland",
    "Friesland",
    "Gelderland",
    "Groningen",
    "Limburg",
    "North Brabant",
    "North Holland",
    "Overijssel",
    "South Holland",
    "Utrecht",
    "Zeeland",
  ],
  "New Zealand": [
    "Northland",
    "Auckland",
    "Waikato",
    "Bay of Plenty",
    "Gisborne",
    "Hawke's Bay",
    "Taranaki",
    "Manawatu-Wanganui",
    "Wellington",
    "Tasman",
    "Nelson",
    "Marlborough",
    "West Coast",
    "Canterbury",
    "Otago",
    "Southland",
  ],
  Nicaragua: [
    "Boaco",
    "Carazo",
    "Chinandega",
    "Chontales",
    "Estelí",
    "Granada",
    "Jinotega",
    "León",
    "Madriz",
    "Managua",
    "Masaya",
    "Matagalpa",
    "Nueva Segovia",
    "Río San Juan",
    "Rivas",
    "Costa Caribe Norte",
    "Costa Caribe Sur",
  ],
  Niger: [
    "Agadez",
    "Diffa",
    "Dosso",
    "Maradi",
    "Tahoua",
    "Tillabéri",
    "Zinder",
    "Niamey",
  ],
  Nigeria: [
    "Abia",
    "Adamawa",
    "Akwa Ibom",
    "Anambra",
    "Bauchi",
    "Bayelsa",
    "Benue",
    "Borno",
    "Cross River",
    "Delta",
    "Ebonyi",
    "Edo",
    "Ekiti",
    "Enugu",
    "Gombe",
    "Imo",
    "Jigawa",
    "Kaduna",
    "Kano",
    "Katsina",
    "Kebbi",
    "Kogi",
    "Kwara",
    "Lagos",
    "Nasarawa",
    "Niger",
    "Ogun",
    "Ondo",
    "Osun",
    "Oyo",
    "Plateau",
    "Rivers",
    "Sokoto",
    "Taraba",
    "Yobe",
    "Zamfara",
    "Federal Capital Territory",
  ],
  Norway: [
    "Agder",
    "Innlandet",
    "Møre og Romsdal",
    "Nordland",
    "Oslo",
    "Rogaland",
    "Troms og Finnmark",
    "Trøndelag",
    "Vestfold og Telemark",
    "Vestland",
    "Viken",
  ],
  Oman: [
    "Ad Dakhiliyah",
    "Al Batinah North",
    "Al Batinah South",
    "Al Buraimi",
    "Al Dhahirah",
    "Al Janubiyah",
    "Al Wusta",
    "Ash Sharqiyah North",
    "Ash Sharqiyah South",
    "Dhofar",
    "Musandam",
    "Muscat",
  ],
  Pakistan: [
    "Azad Kashmir",
    "Balochistan",
    "Federally Administered Tribal Areas",
    "Gilgit-Baltistan",
    "Islamabad Capital Territory",
    "Khyber Pakhtunkhwa",
    "Punjab",
    "Sindh",
  ],
  Palau: [
    "Aimeliik",
    "Airai",
    "Angaur",
    "Hatohobei",
    "Kayangel",
    "Koror",
    "Melekeok",
    "Ngaraard",
    "Ngardmau",
    "Ngatpang",
    "Ngchesar",
    "Ngiwal",
    "Peleliu",
    "Sonsorol",
  ],
  Panama: [
    "Bocas del Toro",
    "Chiriquí",
    "Coclé",
    "Colón",
    "Darién",
    "Herrera",
    "Los Santos",
    "Panamá",
    "Veraguas",
    "Emberá-Wounaan",
    "Guna Yala",
    "Ngöbe-Buglé",
    "Panamá Oeste",
  ],
  "Papua New Guinea": [
    "Central",
    "Chimbu",
    "Eastern Highlands",
    "East New Britain",
    "East Sepik",
    "Enga",
    "Gulf",
    "Hela",
    "Jiwaka",
    "Madang",
    "Manus",
    "Milne Bay",
    "Morobe",
    "New Ireland",
    "Northern",
    "Bougainville",
    "Southern Highlands",
    "Western",
    "Western Highlands",
    "West New Britain",
    "Sandaun",
    "National Capital District",
  ],
  Paraguay: [
    "Alto Paraguay",
    "Alto Paraná",
    "Amambay",
    "Boquerón",
    "Caaguazú",
    "Caazapá",
    "Canindeyú",
    "Central",
    "Concepción",
    "Cordillera",
    "Guairá",
    "Itapúa",
    "Misiones",
    "Ñeembucú",
    "Paraguarí",
    "Presidente Hayes",
    "San Pedro",
  ],
  Peru: [
    "Amazonas",
    "Áncash",
    "Apurímac",
    "Arequipa",
    "Ayacucho",
    "Cajamarca",
    "Callao",
    "Cusco",
    "Huancavelica",
    "Huánuco",
    "Ica",
    "Junín",
    "La Libertad",
    "Lambayeque",
    "Lima",
    "Loreto",
    "Madre de Dios",
    "Moquegua",
    "Pasco",
    "Piura",
    "Puno",
    "San Martín",
    "Tacna",
    "Tumbes",
    "Ucayali",
  ],
  Philippines: [
    "Abra",
    "Agusan del Norte",
    "Agusan del Sur",
    "Aklan",
    "Albay",
    "Antique",
    "Apayao",
    "Aurora",
    "Basilan",
    "Bataan",
    "Batanes",
    "Benguet",
    "Biliran",
    "Bohol",
    "Bukidnon",
    "Bulacan",
    "Cagayan",
    "Caloocan",
    "Camarines Norte",
    "Camarines Sur",
    "Camiguin",
    "Capiz",
    "Catanduanes",
    "Cavite",
    "Cebu",
    "Compostela Valley",
    "Cotabato",
    "Davao del Norte",
    "Davao del Sur",
    "Davao Occidental",
    "Davao Oriental",
    "Dinagat Islands",
    "Eastern Samar",
    "Guimaras",
    "Ifugao",
    "Ilocos Norte",
    "Ilocos Sur",
    "Iloilo",
    "Isabela",
    "Kalinga",
    "La Union",
    "Laguna",
    "Lanao del Norte",
    "Lanao del Sur",
    "Las Piñas",
    "Leyte",
    "Maguindanao",
    "Makati",
    "Malabon",
    "Mandaluyong",
    "Marinduque",
    "Masbate",
    "Muntinlupa",
    "Navotas",
    "Negros Occidental",
    "Negros Oriental",
    "Northern Samar",
    "Nueva Ecija",
    "Nueva Vizcaya",
    "Occidental Mindoro",
    "Oriental Mindoro",
    "Palawan",
    "Pampanga",
    "Pangasinan",
    "Parañaque",
    "Pasay",
    "Pasig",
    "Quezon",
    "Quirino",
    "Rizal",
    "Romblon",
    "San Juan",
    "Sarangani",
    "Siquijor",
    "Sorsogon",
    "South Cotabato",
    "Southern Leyte",
    "Sultan Kudarat",
    "Sulu",
    "Surigao del Norte",
    "Surigao del Sur",
    "Taguig",
    "Tarlac",
    "Tawi-Tawi",
    "Valenzuela",
    "Zambales",
    "Zamboanga del Norte",
    "Zamboanga del Sur",
    "Zamboanga Sibugay",
  ],
  Poland: [
    "Lower Silesian",
    "Kujavian-Pomeranian",
    "Lublin",
    "Lubusz",
    "Łódź",
    "Lesser Poland",
    "Masovian",
    "Opole",
    "Subcarpathian",
    "Pomeranian",
    "Silesian",
    "Holy Cross",
    "Warmian-Masurian",
    "Greater Poland",
    "West Pomeranian",
  ],
  Portugal: [
    "Aveiro",
    "Beja",
    "Braga",
    "Bragança",
    "Castelo Branco",
    "Coimbra",
    "Évora",
    "Faro",
    "Guarda",
    "Leiria",
    "Lisbon",
    "Portalegre",
    "Porto",
    "Santarém",
    "Setúbal",
    "Viana do Castelo",
    "Vila Real",
    "Viseu",
    "Açores",
    "Madeira",
  ],
  Qatar: [
    "Al Daayen",
    "Al Khor",
    "Al Rayyan",
    "Al Shamal",
    "Al Wakrah",
    "Doha",
    "Umm Salal",
  ],
  Romania: [
    "Alba",
    "Arad",
    "Argeș",
    "Bacău",
    "Bihor",
    "Bistrița-Năsăud",
    "Botoșani",
    "Brașov",
    "Brăila",
    "Bucharest",
    "Buzău",
    "Caraș-Severin",
    "Călărași",
    "Cluj",
    "Constanța",
    "Covasna",
    "Dâmbovița",
    "Dolj",
    "Galați",
    "Giurgiu",
    "Gorj",
    "Harghita",
    "Hunedoara",
    "Ialomița",
    "Iași",
    "Ilfov",
    "Maramureș",
    "Mehedinți",
    "Mureș",
    "Neamț",
    "Olt",
    "Prahova",
    "Sălaj",
    "Satu Mare",
    "Sibiu",
    "Suceava",
    "Teleorman",
    "Timiș",
    "Tulcea",
    "Vaslui",
    "Vâlcea",
    "Vrancea",
  ],
  Russia: [
    "Adygea Republic",
    "Altai Krai",
    "Altai Republic",
    "Amur Oblast",
    "Arkhangelsk Oblast",
    "Astrakhan Oblast",
    "Bashkortostan Republic",
    "Belgorod Oblast",
    "Bryansk Oblast",
    "Buryatia Republic",
    "Chechen Republic",
    "Chelyabinsk Oblast",
    "Chukotka Autonomous Okrug",
    "Chuvash Republic",
    "Dagestan Republic",
    "Irkutsk Oblast",
    "Ivanovo Oblast",
    "Jewish Autonomous Oblast",
    "Kabardino-Balkarian Republic",
    "Kaliningrad Oblast",
    "Kalmykia Republic",
    "Kaluga Oblast",
    "Kamchatka Krai",
    "Karachay-Cherkess Republic",
    "Karelia Republic",
    "Kemerovo Oblast",
    "Khabarovsk Krai",
    "Khakassia Republic",
    "Khanty-Mansi Autonomous Okrug",
    "Kirov Oblast",
    "Komi Republic",
    "Kostroma Oblast",
    "Krasnodar Krai",
    "Krasnoyarsk Krai",
    "Kurgan Oblast",
    "Kursk Oblast",
    "Leningrad Oblast",
    "Lipetsk Oblast",
    "Magadan Oblast",
    "Mariy El Republic",
    "Mordovia Republic",
    "Moscow",
    "Moscow Oblast",
    "Murmansk Oblast",
    "Nenets Autonomous Okrug",
    "Nizhny Novgorod Oblast",
    "North Ossetia-Alania Republic",
    "Novgorod Oblast",
    "Novosibirsk Oblast",
    "Omsk Oblast",
    "Orenburg Oblast",
    "Orel Oblast",
    "Penza Oblast",
    "Perm Krai",
    "Primorsky Krai",
    "Pskov Oblast",
    "Rostov Oblast",
    "Ryazan Oblast",
    "Saint Petersburg",
    "Sakha Republic",
    "Sakhalin Oblast",
    "Samara Oblast",
    "Saratov Oblast",
    "Sevastopol",
    "Smolensk Oblast",
    "Stavropol Krai",
    "Sverdlovsk Oblast",
    "Tambov Oblast",
    "Tatarstan Republic",
    "Tomsk Oblast",
    "Tula Oblast",
    "Tyumen Oblast",
    "Tuva Republic",
    "Udmurt Republic",
    "Ulyanovsk Oblast",
    "Vladimir Oblast",
    "Volgograd Oblast",
    "Vologda Oblast",
    "Voronezh Oblast",
    "Yamalo-Nenets Autonomous Okrug",
    "Yaroslavl Oblast",
    "Zabaykalsky Krai",
  ],
  Rwanda: ["East", "Kigali", "North", "South", "West"],
  "Saint Kitts and Nevis": [
    "Christ Church Nichola Town",
    "Saint Anne Sandy Point",
    "Saint George Basseterre",
    "Saint George Gingerland",
    "Saint James Windward",
    "Saint John Capisterre",
    "Saint John Figtree",
    "Saint Mary Cayon",
    "Saint Paul Capisterre",
    "Saint Paul Charlestown",
    "Saint Peter Basseterre",
    "Saint Thomas Lowland",
    "Trinity Palmetto Point",
    "Nevis",
  ],
  "Saint Lucia": [
    "Anse la Raye Quarter",
    "Castries Quarter",
    "Choiseul Quarter",
    "Dauphin Quarter",
    "Dennery Quarter",
    "Gros Islet Quarter",
    "Laborie Quarter",
    "Micoud Quarter",
    "Praslin Quarter",
    "Soufrière Quarter",
    "Vieux Fort Quarter",
  ],
  "Saint Vincent and the Grenadines": [
    "Charlotte Parish",
    "Grenadines Parish",
    "Saint Andrew Parish",
    "Saint David Parish",
    "Saint George Parish",
    "Saint Patrick Parish",
  ],
  Samoa: [
    "A'ana",
    "Aiga-i-le-Tai",
    "Atua",
    "Fa'asaleleaga",
    "Gaga'emauga",
    "Gagaifomauga",
    "Palauli",
    "Satupa'itea",
    "Tuamasaga",
    "Va'a-o-Fonoti",
    "Vaisigano",
  ],
  "San Marino": [
    "Acquaviva",
    "Borgo Maggiore",
    "Chiesanuova",
    "Domagnano",
    "Faetano",
    "Fiorentino",
    "Montegiardino",
    "San Marino",
    "Serravalle",
  ],
  "São Tomé and Príncipe": [
    "Água Grande",
    "Cantagalo",
    "Caué",
    "Lembá",
    "Lobata",
    "Mé-Zóchi",
    "Pagué",
  ],
  "Saudi Arabia": [
    "Al Bahah",
    "Al Hudud ash Shamaliyah",
    "Al Jawf",
    "Al Madinah al Munawwarah",
    "Al Qassim",
    "Ar Riyad",
    "Asir",
    "Ha'il",
    "Jazan",
    "Makkah",
    "Najran",
    "Qassim",
    "Tabuk",
    "Eastern Province",
  ],
  Senegal: [
    "Dakar",
    "Diourbel",
    "Fatick",
    "Kaffrine",
    "Kaolack",
    "Kédougou",
    "Kolda",
    "Louga",
    "Matam",
    "Saint-Louis",
    "Sédhiou",
    "Tambacounda",
    "Thiès",
    "Ziguinchor",
  ],
  Serbia: [
    "Vojvodina",
    "Šumadija and Western Serbia",
    "Southern and Eastern Serbia",
    "Belgrade",
  ],
  Seychelles: [
    "Anse aux Pins",
    "Anse Boileau",
    "Anse Étoile",
    "Au Cap",
    "Baie Lazare",
    "Baie Sainte Anne",
    "Beau Vallon",
    "Bel Air",
    "Bel Ombre",
    "Cascade",
    "Glacis",
    "Grand Anse Mahé",
    "Grand Anse Praslin",
    "Les Mamelles",
    "Mont Buxton",
    "Mont Fleuri",
    "Plaisance",
    "Pointe La Rue",
    "Port Glaud",
    "Roche Caiman",
    "Saint Louis",
    "Takamaka",
  ],
  "Sierra Leone": [
    "Eastern Province",
    "Northern Province",
    "Southern Province",
    "Western Area",
  ],
  Singapore: [
    "Central Region",
    "East Region",
    "North Region",
    "North-East Region",
    "West Region",
  ],
  Slovakia: [
    "Banská Bystrica Region",
    "Bratislava Region",
    "Košice Region",
    "Nitra Region",
    "Prešov Region",
    "Trenčín Region",
    "Trnava Region",
    "Žilina Region",
  ],
  Slovenia: [
    "Goriška",
    "Gorenjska",
    "Jugovzhodna Slovenija",
    "Koroška",
    "Notranjsko-kraška",
    "Obalno-kraška",
    "Osrednjeslovenska",
    "Podravska",
    "Pomurska",
    "Posavska",
    "Primorsko-notranjska",
    "Savinjska",
    "Zasavska",
  ],
  "Solomon Islands": [
    "Central Province",
    "Choiseul Province",
    "Guadalcanal Province",
    "Isabel Province",
    "Makira-Ulawa Province",
    "Malaita Province",
    "Rennell and Bellona Province",
    "Temotu Province",
    "Western Province",
    "Honiara",
  ],
  Somalia: [
    "Banadir",
    "Bari",
    "Bay",
    "Galguduud",
    "Gedo",
    "Hiran",
    "Lower Juba",
    "Middle Juba",
    "Lower Shabelle",
    "Middle Shabelle",
    "Mudug",
    "Nugal",
    "Sanaag",
    "Sool",
    "Togdheer",
    "Woqooyi Galbeed",
  ],
  "South Africa": [
    "Eastern Cape",
    "Free State",
    "Gauteng",
    "KwaZulu-Natal",
    "Limpopo",
    "Mpumalanga",
    "North West",
    "Northern Cape",
    "Western Cape",
  ],
  "South Korea": [
    "Busan",
    "Chungcheongbuk-do",
    "Chungcheongnam-do",
    "Daegu",
    "Daejeon",
    "Gangwon-do",
    "Gwangju",
    "Gyeonggi-do",
    "Gyeongsangbuk-do",
    "Gyeongsangnam-do",
    "Incheon",
    "Jeju-do",
    "Jeollabuk-do",
    "Jeollanam-do",
    "Sejong",
    "Seoul",
    "Ulsan",
  ],
  "South Sudan": [
    "Central Equatoria",
    "Eastern Equatoria",
    "Jonglei",
    "Lakes",
    "Northern Bahr el Ghazal",
    "Unity",
    "Upper Nile",
    "Warrap",
    "Western Bahr el Ghazal",
    "Western Equatoria",
    "Abyei Area",
    "Ruweng Administrative Area",
    "Pibor Administrative Area",
  ],
  Spain: [
    "Andalusia",
    "Aragon",
    "Asturias",
    "Balearic Islands",
    "Basque Country",
    "Canary Islands",
    "Cantabria",
    "Castile and León",
    "Castile-La Mancha",
    "Catalonia",
    "Extremadura",
    "Galicia",
    "La Rioja",
    "Madrid",
    "Murcia",
    "Navarre",
    "Valencian Community",
  ],
  "Sri Lanka": [
    "Central Province",
    "Eastern Province",
    "North Central Province",
    "North Western Province",
    "Northern Province",
    "Sabaragamuwa Province",
    "Southern Province",
    "Uva Province",
    "Western Province",
  ],
  Sudan: [
    "Al Jazirah",
    "Al Khartum",
    "Blue Nile",
    "Central Darfur",
    "East Darfur",
    "Gedaref",
    "Kassala",
    "North Darfur",
    "North Kordofan",
    "Red Sea",
    "River Nile",
    "Sennar",
    "South Darfur",
    "South Kordofan",
    "White Nile",
    "West Darfur",
    "West Kordofan",
  ],
  Suriname: [
    "Brokopondo",
    "Commewijne",
    "Coronie",
    "Marowijne",
    "Nickerie",
    "Para",
    "Paramaribo",
    "Saramacca",
    "Sipaliwini",
    "Wanica",
  ],
  Sweden: [
    "Blekinge County",
    "Dalarna County",
    "Gävleborg County",
    "Gotland County",
    "Halland County",
    "Jämtland County",
    "Jönköping County",
    "Kalmar County",
    "Kronoberg County",
    "Norrbotten County",
    "Örebro County",
    "Östergötland County",
    "Skåne County",
    "Södermanland County",
    "Stockholm County",
    "Uppsala County",
    "Värmland County",
    "Västerbotten County",
    "Västernorrland County",
    "Västmanland County",
    "Västra Götaland County",
  ],
  Switzerland: [
    "Aargau",
    "Appenzell Ausserrhoden",
    "Appenzell Innerrhoden",
    "Basel-Landschaft",
    "Basel-Stadt",
    "Bern",
    "Fribourg",
    "Geneva",
    "Glarus",
    "Graubünden",
    "Jura",
    "Lucerne",
    "Neuchâtel",
    "Nidwalden",
    "Obwalden",
    "Schaffhausen",
    "Schwyz",
    "Solothurn",
    "St. Gallen",
    "Thurgau",
    "Ticino",
    "Uri",
    "Valais",
    "Vaud",
    "Zug",
    "Zürich",
  ],
  Syria: [
    "Al Hasakah",
    "Al Ladhiqiyah",
    "Al Qunaytirah",
    "Ar Raqqah",
    "As Suwayda",
    "Dar'a",
    "Dayr az Zawr",
    "Dimashq",
    "Halab",
    "Hama",
    "Hims",
    "Idlib",
    "Rif Dimashq",
    "Tartus",
  ],
  Taiwan: [
    "Changhua County",
    "Chiayi City",
    "Chiayi County",
    "Hsinchu County",
    "Hsinchu City",
    "Hualien County",
    "Kaohsiung",
    "Keelung",
    "Kinmen County",
    "Lienchiang County",
    "Miaoli County",
    "Nantou County",
    "New Taipei",
    "Penghu County",
    "Pingtung County",
    "Taichung",
    "Tainan",
    "Taipei",
    "Taitung County",
    "Taoyuan",
    "Yilan County",
    "Yunlin County",
  ],
  Tajikistan: [
    "Sughd Province",
    "Khatlon Province",
    "Gorno-Badakhshan Autonomous Region",
    "Districts of Republican Subordination",
    "Dushanbe",
  ],
  Tanzania: [
    "Arusha",
    "Dar es Salaam",
    "Dodoma",
    "Geita",
    "Iringa",
    "Kagera",
    "Katavi",
    "Kigoma",
    "Kilimanjaro",
    "Lindi",
    "Manyara",
    "Mara",
    "Mbeya",
    "Mjini Magharibi",
    "Morogoro",
    "Mtwara",
    "Mwanza",
    "Njombe",
    "Pemba North",
    "Pemba South",
    "Pwani",
    "Rukwa",
    "Ruvuma",
    "Shinyanga",
    "Simiyu",
    "Singida",
    "Songwe",
    "Tabora",
    "Tanga",
    "Unguja North",
    "Unguja South",
    "Unguja Urban West",
  ],
  Thailand: [
    "Amnat Charoen",
    "Ang Thong",
    "Bangkok",
    "Bueng Kan",
    "Buriram",
    "Chachoengsao",
    "Chainat",
    "Chaiyaphum",
    "Chanthaburi",
    "Chiang Mai",
    "Chiang Rai",
    "Chonburi",
    "Chumphon",
    "Kalasin",
    "Kamphaeng Phet",
    "Kanchanaburi",
    "Khon Kaen",
    "Krabi",
    "Lampang",
    "Lamphun",
    "Loei",
    "Lopburi",
    "Mae Hong Son",
    "Maha Sarakham",
    "Mukdahan",
    "Nakhon Nayok",
    "Nakhon Pathom",
    "Nakhon Phanom",
    "Nakhon Ratchasima",
    "Nakhon Sawan",
    "Nakhon Si Thammarat",
    "Nan",
    "Narathiwat",
    "Nong Bua Lamphu",
    "Nong Khai",
    "Nonthaburi",
    "Pathum Thani",
    "Pattani",
    "Phang Nga",
    "Phatthalung",
    "Phayao",
    "Phetchabun",
    "Phetchaburi",
    "Phichit",
    "Phitsanulok",
    "Phrae",
    "Phuket",
    "Prachinburi",
    "Prachuap Khiri Khan",
    "Ranong",
    "Ratchaburi",
    "Rayong",
    "Roi Et",
    "Sa Kaeo",
    "Sakon Nakhon",
    "Samut Prakan",
    "Samut Sakhon",
    "Samut Songkhram",
    "Sara Buri",
    "Satun",
    "Sing Buri",
    "Sisaket",
    "Songkhla",
    "Sukhothai",
    "Suphan Buri",
    "Surat Thani",
    "Surin",
    "Tak",
    "Trang",
    "Trat",
    "Ubon Ratchathani",
    "Udon Thani",
    "Uthai Thani",
    "Uttaradit",
    "Yala",
    "Yasothon",
  ],
  "Timor-Leste": [
    "Aileu Municipality",
    "Ainaro Municipality",
    "Baucau Municipality",
    "Bobonaro Municipality",
    "Cova Lima Municipality",
    "Dili Municipality",
    "Ermera Municipality",
    "Lautém Municipality",
    "Liquiçá Municipality",
    "Manatuto Municipality",
    "Manufahi Municipality",
    "Oecusse Municipality",
    "Viqueque Municipality",
    "Railaco",
    "Maliana",
  ],
  Togo: [
    "Centrale Region",
    "Kara Region",
    "Maritime",
    "Plateaux Region",
    "Savanes Region",
  ],
  Tonga: ["Haʻapai", "ʻEua", "Niuas", "Tongatapu", "Vavaʻu"],
  "Trinidad and Tobago": [
    "Arima",
    "Couva-Tabaquite-Talparo",
    "Diego Martin",
    "Eastern Tobago",
    "Penal-Debe",
    "Point Fortin",
    "Port of Spain",
    "Princes Town",
    "Rio Claro-Mayaro",
    "San Fernando",
    "Sangre Grande",
    "San Juan-Laventille",
    "Siparia",
    "Tunapuna-Piarco",
    "Western Tobago",
  ],
  Tunisia: [
    "Ariana Governorate",
    "Béja Governorate",
    "Ben Arous Governorate",
    "Bizerte Governorate",
    "Gabès Governorate",
    "Gafsa Governorate",
    "Jendouba Governorate",
    "Kairouan Governorate",
    "Kasserine Governorate",
    "Kébili Governorate",
    "Kef Governorate",
    "Mahdia Governorate",
    "Manouba Governorate",
    "Medenine Governorate",
    "Monastir Governorate",
    "Nabeul Governorate",
    "Sfax Governorate",
    "Sidi Bouzid Governorate",
    "Siliana Governorate",
    "Sousse Governorate",
    "Tataouine Governorate",
    "Tozeur Governorate",
    "Tunis Governorate",
    "Zaghouan Governorate",
  ],
  Turkey: [
    "Adana",
    "Adıyaman",
    "Afyonkarahisar",
    "Ağrı",
    "Aksaray",
    "Amasya",
    "Ankara",
    "Antalya",
    "Ardahan",
    "Artvin",
    "Aydın",
    "Balıkesir",
    "Bartın",
    "Batman",
    "Bayburt",
    "Bilecik",
    "Bingöl",
    "Bitlis",
    "Bolu",
    "Burdur",
    "Bursa",
    "Çanakkale",
    "Çankırı",
    "Çorum",
    "Denizli",
    "Diyarbakır",
    "Düzce",
    "Edirne",
    "Elazığ",
    "Erzincan",
    "Erzurum",
    "Eskişehir",
    "Gaziantep",
    "Giresun",
    "Gümüşhane",
    "Hakkari",
    "Hatay",
    "Iğdır",
    "Isparta",
    "İstanbul",
    "İzmir",
    "Kahramanmaraş",
    "Karabük",
    "Karaman",
    "Kars",
    "Kastamonu",
    "Kayseri",
    "Kırıkkale",
    "Kırklareli",
    "Kırşehir",
    "Kilis",
    "Kocaeli",
    "Konya",
    "Kütahya",
    "Malatya",
    "Manisa",
    "Mardin",
    "Mersin",
    "Muğla",
    "Muş",
    "Nevşehir",
    "Niğde",
    "Ordu",
    "Osmaniye",
    "Rize",
    "Sakarya",
    "Samsun",
    "Şanlıurfa",
    "Siirt",
    "Sinop",
    "Sivas",
    "Şırnak",
    "Tekirdağ",
    "Tokat",
    "Trabzon",
    "Tunceli",
    "Uşak",
    "Van",
    "Yalova",
    "Yozgat",
    "Zonguldak",
  ],
  Turkmenistan: [
    "Ahal Region",
    "Balkan Region",
    "Dashoguz Region",
    "Lebap Region",
    "Mary Region",
    "Ashgabat",
  ],
  Tuvalu: [
    "Funafuti",
    "Nanumea",
    "Nui",
    "Nukufetau",
    "Nukulaelae",
    "Vaitupu",
    "Niutao",
    "Nanumaga",
  ],
  Uganda: [
    "Abim District",
    "Adjumani District",
    "Agago District",
    "Alebtong District",
    "Amolatar District",
    "Amudat District",
    "Amuria District",
    "Amuru District",
    "Apac District",
    "Arua District",
    "Budaka District",
    "Bududa District",
    "Bugiri District",
    "Buhweju District",
    "Buikwe District",
    "Bukedea District",
    "Bukomansimbi District",
    "Bukwo District",
    "Bulambuli District",
    "Buliisa District",
    "Bundibugyo District",
    "Bushenyi District",
    "Busia District",
    "Butaleja District",
    "Butebo District",
    "Buvuma District",
    "Buyende District",
    "Central Region",
    "Eastern Region",
    "Gomba District",
    "Gulu District",
    "Hoima District",
    "Ibanda District",
    "Iganga District",
    "Isingiro District",
    "Jinja District",
    "Kaabong District",
    "Kabale District",
    "Kabarole District",
    "Kaberamaido District",
    "Kagadi District",
    "Kakumiro District",
    "Kalangala District",
    "Kaliro District",
    "Kalungu District",
    "Kampala District",
    "Kamuli District",
    "Kamwenge District",
    "Kanungu District",
    "Kapchorwa District",
    "Kasese District",
    "Katakwi District",
    "Kayunga District",
    "Kibaale District",
    "Kiboga District",
    "Kibuku District",
    "Kigarama District",
    "Kiruhura District",
    "Kiryandongo District",
    "Kisoro District",
    "Kitgum District",
    "Koboko District",
    "Kole District",
    "Kotido District",
    "Kumi District",
    "Kween District",
    "Kyankwanzi District",
    "Kyegegwa District",
    "Kyenjojo District",
    "Kyotera District",
    "Lamwo District",
    "Lira District",
    "Luuka District",
    "Luweero District",
    "Lwengo District",
    "Lyantonde District",
    "Manafwa District",
    "Maracha District",
    "Masaka District",
    "Masindi District",
    "Mayuge District",
    "Mbale District",
    "Mbarara District",
    "Mitooma District",
    "Mityana District",
    "Moroto District",
    "Moyo District",
    "Mpigi District",
    "Mubende District",
    "Mukono District",
    "Nakapiripirit District",
    "Nakasongola District",
    "Namayingo District",
    "Namisindwa District",
    "Namutumba District",
    "Napak District",
    "Nebbi District",
    "Ngora District",
    "Northern Region",
    "Ntoroko District",
    "Ntungamo District",
    "Nwoya District",
    "Omoro District",
    "Otuke District",
    "Oyam District",
    "Pader District",
    "Pakwach District",
    "Pallisa District",
    "Rakai District",
    "Rubanda District",
    "Rubirizi District",
    "Rukungiri District",
    "Serere District",
    "Sheema District",
    "Sironko District",
    "Soroti District",
    "Southwestern Region",
    "Tororo District",
    "Wakiso District",
    "Western Region",
    "Yumbe District",
    "Zombo District",
  ],
  Ukraine: [
    "Cherkasy Oblast",
    "Chernihiv Oblast",
    "Chernivtsi Oblast",
    "Dnipropetrovsk Oblast",
    "Donetsk Oblast",
    "Ivano-Frankivsk Oblast",
    "Kharkiv Oblast",
    "Kherson Oblast",
    "Khmelnytskyi Oblast",
    "Kiev",
    "Kiev Oblast",
    "Kirovohrad Oblast",
    "Luhansk Oblast",
    "Lviv Oblast",
    "Mykolaiv Oblast",
    "Odessa Oblast",
    "Poltava Oblast",
    "Rivne Oblast",
    "Sevastopol",
    "Sumy Oblast",
    "Ternopil Oblast",
    "Transcarpathian Oblast",
    "Vinnytsia Oblast",
    "Volyn Oblast",
    "Zaporizhia Oblast",
    "Zhytomyr Oblast",
    "Crimea",
  ],
  "United Arab Emirates": [
    "Abu Dhabi",
    "Ajman",
    "Dubai",
    "Fujairah",
    "Ras Al Khaimah",
    "Sharjah",
    "Umm Al Quwain",
  ],
  "United Kingdom": ["England", "Scotland", "Wales", "Northern Ireland"],
  "United States": [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
  ],
  Uruguay: [
    "Artigas",
    "Canelones",
    "Cerro Largo",
    "Colonia",
    "Durazno",
    "Flores",
    "Florida",
    "Lavalleja",
    "Maldonado",
    "Montevideo",
    "Paysandú",
    "Río Negro",
    "Rivera",
    "Rocha",
    "Salto",
    "San José",
    "Soriano",
    "Tacuarembó",
    "Treinta y Tres",
  ],
  Uzbekistan: [
    "Tashkent",
    "Andijan Region",
    "Bukhara Region",
    "Fergana Region",
    "Jizzakh Region",
    "Karakalpakstan",
    "Kashkadarya Region",
    "Khorezm Region",
    "Namangan Region",
    "Navoiy Region",
    "Samarqand Region",
    "Sirdarya Region",
    "Surkhandarya Region",
  ],
  Vanuatu: ["Malampa", "Penama", "Sanma", "Shefa", "Tafea", "Torba"],
  Venezuela: [
    "Amazonas",
    "Anzoátegui",
    "Apure",
    "Aragua",
    "Barinas",
    "Bolívar",
    "Carabobo",
    "Cojedes",
    "Delta Amacuro",
    "Falcón",
    "Guárico",
    "Lara",
    "Mérida",
    "Miranda",
    "Monagas",
    "Nueva Esparta",
    "Portuguesa",
    "Sucre",
    "Táchira",
    "Trujillo",
    "Vargas",
    "Yaracuy",
    "Zulia",
    "Distrito Capital",
    "Dependencias Federales",
  ],
  Vietnam: [
    "An Giang",
    "Bà Rịa-Vũng Tàu",
    "Bắc Giang",
    "Bắc Kạn",
    "Bạc Liêu",
    "Bắc Ninh",
    "Bến Tre",
    "Bình Định",
    "Bình Dương",
    "Bình Phước",
    "Bình Thuận",
    "Cà Mau",
    "Cần Thơ",
    "Cao Bằng",
    "Đà Nẵng",
    "Đắk Lắk",
    "Đắk Nông",
    "Điện Biên",
    "Đồng Nai",
    "Đồng Tháp",
    "Gia Lai",
    "Hà Giang",
    "Hà Nam",
    "Hà Nội",
    "Hà Tĩnh",
    "Hải Dương",
    "Hải Phòng",
    "Hậu Giang",
    "Hòa Bình",
    "Hưng Yên",
    "Khánh Hòa",
    "Kiên Giang",
    "Kon Tum",
    "Lai Châu",
    "Lạng Sơn",
    "Lào Cai",
    "Long An",
    "Nam Định",
    "Nghệ An",
    "Ninh Bình",
    "Ninh Thuận",
    "Phú Thọ",
    "Phú Yên",
    "Quảng Bình",
    "Quảng Nam",
    "Quảng Ngãi",
    "Quảng Ninh",
    "Quảng Trị",
    "Sóc Trăng",
    "Sơn La",
    "Tây Ninh",
    "Thái Bình",
    "Thái Nguyên",
    "Thanh Hóa",
    "Thừa Thiên Huế",
    "Tiền Giang",
    "Trà Vinh",
    "Tuyên Quang",
    "Vĩnh Long",
    "Vĩnh Phúc",
    "Yên Bái",
  ],
  Yemen: [
    "Abyan",
    "Aden",
    "Al Bayda",
    "Al Hudaydah",
    "Al Jawf",
    "Al Mahrah",
    "Al Mahwit",
    "Amanat Al Asimah",
    "Dhamar",
    "Hadhramaut",
    "Hajjah",
    "Ibb",
    "Lahij",
    "Ma'rib",
    "Raymah",
    "Saada",
    "Sana'a",
    "Shabwah",
    "Taiz",
  ],
  Zambia: [
    "Central Province",
    "Copperbelt Province",
    "Eastern Province",
    "Luapula Province",
    "Lusaka Province",
    "Muchinga Province",
    "North-Western Province",
    "Northern Province",
    "Southern Province",
    "Western Province",
  ],
  Zimbabwe: [
    "Bulawayo",
    "Harare",
    "Manicaland",
    "Mashonaland Central",
    "Mashonaland East",
    "Mashonaland West",
    "Masvingo",
    "Matabeleland North",
    "Matabeleland South",
    "Midlands",
  ],
};

export default countryStateData;
